using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Stack.UI;

[GenerateTypedNameReferences]
public sealed partial class StackSplitWindow : DefaultWindow
{
    public event Action<int>? OnConfirmed;

    private readonly int _max;

    private bool _updating;

    private int CurrentAmount
    {
        get
        {
            if (int.TryParse(AmountField.Text, out var amount))
                return Math.Clamp(amount, 1, _max);
            return Math.Clamp((int)AmountSlider.Value, 1, _max);
        }
    }

    private void SetAmount(int amount)
    {
        amount = Math.Clamp(amount, 1, _max);

        _updating = true;
        AmountSlider.Value = amount;
        AmountField.Text = amount.ToString();
        AmountSuffix.Text = Loc.GetString("stack-split-window-amount-suffix", ("max", _max));
        _updating = false;
    }

    public StackSplitWindow(int max, int initial = 1)
    {
        RobustXamlLoader.Load(this);

        _max = Math.Max(1, max);

        AmountSlider.MinValue = 1;
        AmountSlider.MaxValue = _max;

        SetAmount(initial);

        AmountSlider.OnValueChanged += _ =>
        {
            if (_updating)
                return;
            SetAmount((int) AmountSlider.Value);
        };

        AmountField.OnTextChanged += _ =>
        {
            if (_updating || int.TryParse(AmountField.Text, out var value))
                return;
            SetAmount(value);
        };

        SplitButton.OnPressed += _ =>
        {
            OnConfirmed?.Invoke(CurrentAmount);
            Close();
        };

        Plus1.OnPressed += _ => SetAmount(CurrentAmount + 1);
        Plus10.OnPressed += _ => SetAmount(CurrentAmount + 10);
        Plus100.OnPressed += _ => SetAmount(CurrentAmount + 100);

        Minus1.OnPressed += _ => SetAmount(CurrentAmount - 1);
        Minus10.OnPressed += _ => SetAmount(CurrentAmount - 10);
        Minus100.OnPressed += _ => SetAmount(CurrentAmount - 100);

        CancelButton.OnPressed += _ => Close();
    }
}