using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._Persistence14.Requisitions;
using Content.Shared.Materials;
using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Localization;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Persistence14.Requisitions.UI;

[GenerateTypedNameReferences]
public sealed partial class RequisitionsConsoleMenu : FancyWindow
{
    public event Action<List<RequisitionCartItem>, bool, string, int?>? OnCheckout;
    public event Action? OnCancel;
    public event Action<NetEntity>? OnToggleLink;
    public event Action<string, int>? OnSetMaterialPrice;
    public event Action<RequisitionFee>? OnSetFee;
    public event Action<string>? OnRemoveFee;
    public event Action? OnEjectFlatpacks;
    public event Action<bool>? OnSetDetailedInvoice;

    private readonly IEntityManager _entMan;
    private readonly IPrototypeManager _proto;
    private readonly SharedMaterialStorageSystem _materialStorage;
    private readonly SpriteSystem _sprite;

    private RequisitionsConsoleState _state = new();
    private readonly List<RequisitionCartItem> _cart = new();
    private readonly HashSet<int> _expanded = new();
    private readonly Dictionary<string, bool> _catalogueFlatpack = new();

    // The last calculated order total. The final-price field tracks this and is reset back to it whenever the
    // calculated total changes, discarding any manual edit. -1 forces the field to seed on the first build.
    private int _calculatedTotal = -1;

    public RequisitionsConsoleMenu()
    {
        RobustXamlLoader.Load(this);

        _entMan = IoCManager.Resolve<IEntityManager>();
        _proto = IoCManager.Resolve<IPrototypeManager>();
        _materialStorage = _entMan.System<SharedMaterialStorageSystem>();
        _sprite = _entMan.System<SpriteSystem>();

        Tabs.SetTabTitle(0, Loc.GetString("requisitions-tab-checkout"));
        Tabs.SetTabTitle(1, Loc.GetString("requisitions-tab-config"));

        SearchBar.OnTextChanged += _ => RebuildCatalogue();
        CheckoutButton.OnPressed += _ => Checkout();
        CancelButton.OnPressed += _ =>
        {
            _cart.Clear();
            _expanded.Clear();
            CartChanged();
            OnCancel?.Invoke();
        };
        EjectButton.OnPressed += _ => OnEjectFlatpacks?.Invoke();
        AddFeeButton.OnPressed += _ => AddFee();
        DetailedInvoiceCheck.OnToggled += a => OnSetDetailedInvoice?.Invoke(a.Pressed);
    }

    public void SetEntity(EntityUid owner)
    {
    }

    public void Update(RequisitionsConsoleState state)
    {
        _state = state;

        var valid = state.Catalogue.Select(e => e.RecipeId).ToHashSet();
        _cart.RemoveAll(i => !valid.Contains(i.RecipeId));

        HeaderLabel.Text = Loc.GetString("requisitions-linked-count",
                               ("count", state.Catalogue.Count == 0 ? 0 : state.Catalogue.Max(e => e.SourceCount)))
                           + "  ·  "
                           + Loc.GetString(state.FlatpackerLinked ? "requisitions-flatpacker-online" : "requisitions-flatpacker-offline");

        Tabs.SetTabVisible(1, state.HasConfigAccess);

        // Lock the customer tab while a checkout is still printing.
        ProcessingBanner.Visible = state.Processing;
        SearchBar.Editable = !state.Processing;

        RebuildCatalogue();
        RebuildCart();
        RebuildConfig();
    }

    #region Icon helper

    // Flat textures rather than EntityPrototypeView: the latter spawns a live client entity per icon, which
    // tanks FPS when the whole catalogue/cart/config rebuilds. Frame0 just grabs a static texture.
    private Control MakeTextureRect(float size) => new TextureRect
    {
        MinSize = new Vector2(size, size),
        SetSize = new Vector2(size, size),
        Stretch = TextureRect.StretchMode.KeepAspectCentered,
        VerticalAlignment = VAlignment.Center,
    };

    private Control MakeIcon(string? result, float size = 32)
    {
        var rect = (TextureRect) MakeTextureRect(size);
        if (result != null)
            rect.Texture = _sprite.Frame0(new SpriteSpecifier.EntityPrototype(result));
        return rect;
    }

    private Control MakeMaterialIcon(string matId, float size = 20)
    {
        var rect = (TextureRect) MakeTextureRect(size);
        if (_proto.TryIndex<MaterialPrototype>(matId, out var mat) && mat.StackEntity is { } stack)
            rect.Texture = _sprite.Frame0(new SpriteSpecifier.EntityPrototype(stack));
        return rect;
    }

    #endregion

    #region Catalogue

    private void RebuildCatalogue()
    {
        CatalogueContainer.RemoveAllChildren();
        var filter = SearchBar.Text.Trim();

        foreach (var entry in _state.Catalogue)
        {
            if (filter.Length > 0 && !entry.Name.Contains(filter, StringComparison.OrdinalIgnoreCase))
                continue;

            var recipeId = entry.RecipeId;
            var flatpack = entry.Flatpackable && _catalogueFlatpack.GetValueOrDefault(recipeId);

            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, HorizontalExpand = true, Margin = new Thickness(0, 1) };

            // Live research budget: the shown count drops as this recipe is carted, and adding is blocked at zero.
            var inCart = _cart.Count(i => i.RecipeId == recipeId);
            var soldOut = entry.PrintsRemaining is { } pr && inCart >= pr;

            // Clickable [icon | name | prints] area.
            var button = new ContainerButton { HorizontalExpand = true, Disabled = _state.Processing || soldOut };
            var hb = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, HorizontalExpand = true };
            hb.AddChild(MakeIcon(entry.Result));
            hb.AddChild(new Label
            {
                Text = entry.Name,
                HorizontalExpand = true,
                Margin = new Thickness(6, 0, 0, 0),
                ClipText = true,
            });
            if (entry.PrintsRemaining is { } prints)
            {
                var left = Math.Max(0, prints - inCart);
                hb.AddChild(new Label
                {
                    Text = Loc.GetString("requisitions-prints-remaining", ("count", left)),
                    Margin = new Thickness(6, 0, 0, 0),
                    FontColorOverride = Color.FromHex(left == 0 ? "#d05555" : "#e0a24b"),
                    StyleClasses = { "LabelSubText" },
                });
            }
            button.AddChild(hb);
            button.OnPressed += _ => AddToCart(recipeId, flatpack);
            row.AddChild(button);

            // Flatpack toggle, then price — kept outside the clickable area.
            if (entry.Flatpackable)
            {
                var check = new CheckBox { Text = Loc.GetString("requisitions-flatpack"), Pressed = flatpack, Margin = new Thickness(8, 0, 0, 0) };
                check.OnToggled += a =>
                {
                    _catalogueFlatpack[recipeId] = a.Pressed;
                    RebuildCatalogue();
                };
                row.AddChild(check);
            }

            row.AddChild(new Label { Text = $"${ItemCost(entry, flatpack)}", StyleClasses = { "LabelKeyText" }, Margin = new Thickness(8, 0, 0, 0) });

            CatalogueContainer.AddChild(row);
        }
    }

    private void AddToCart(string recipeId, bool flatpack)
    {
        _cart.Add(new RequisitionCartItem { RecipeId = recipeId, Quantity = 1, Flatpack = flatpack });
        CartChanged();
    }

    /// <summary>The cart changed: refresh both the cart and the catalogue (whose live "prints left" depends on it).</summary>
    private void CartChanged()
    {
        RebuildCatalogue();
        RebuildCart();
    }

    #endregion

    #region Cart

    private void RebuildCart()
    {
        CartContainer.RemoveAllChildren();

        if (_cart.Count == 0)
        {
            CartContainer.AddChild(new Label
            {
                Text = Loc.GetString("requisitions-cart-empty"),
                StyleClasses = { "LabelSubText" },
                Margin = new Thickness(4),
            });
            RebuildTotals();
            return;
        }

        for (var i = 0; i < _cart.Count; i++)
        {
            var index = i;
            var item = _cart[i];
            var entry = _state.Catalogue.FirstOrDefault(e => e.RecipeId == item.RecipeId);
            if (entry == null)
                continue;

            var box = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, HorizontalExpand = true };

            // Header row: [icon | name | cost] click to expand, then flatpack checkbox + remove.
            var header = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, HorizontalExpand = true };

            var expand = new ContainerButton { HorizontalExpand = true };
            var hb = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, HorizontalExpand = true };
            hb.AddChild(new Label { Text = _expanded.Contains(index) ? "▾" : "▸", Margin = new Thickness(0, 0, 4, 0) });
            hb.AddChild(MakeIcon(entry.Result, 28));
            hb.AddChild(new Label { Text = entry.Name, HorizontalExpand = true, Margin = new Thickness(6, 0, 0, 0), ClipText = true });
            hb.AddChild(new Label { Text = $"${ItemCost(entry, item.Flatpack)}", StyleClasses = { "LabelKeyText" } });
            expand.AddChild(hb);
            expand.OnPressed += _ =>
            {
                if (!_expanded.Add(index))
                    _expanded.Remove(index);
                RebuildCart();
            };
            header.AddChild(expand);

            if (entry.Flatpackable)
            {
                var check = new CheckBox { Text = Loc.GetString("requisitions-flatpack"), Pressed = item.Flatpack, Margin = new Thickness(8, 0, 0, 0) };
                check.OnToggled += a =>
                {
                    var it = _cart[index];
                    it.Flatpack = a.Pressed;
                    _cart[index] = it;
                    RebuildCart();
                };
                header.AddChild(check);
            }

            var remove = new Button { Text = "✕", Margin = new Thickness(8, 0, 0, 0), StyleClasses = { "ButtonColorRed" } };
            remove.OnPressed += _ =>
            {
                _cart.RemoveAt(index);
                _expanded.Clear();
                CartChanged();
            };
            header.AddChild(remove);
            box.AddChild(header);

            if (_expanded.Contains(index))
                box.AddChild(BuildCartDetail(entry, item));

            CartContainer.AddChild(box);
        }

        RebuildTotals();
    }

    private Control BuildCartDetail(RequisitionCatalogueEntry entry, RequisitionCartItem item)
    {
        var detail = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, Margin = new Thickness(34, 2, 4, 6) };
        var mult = item.Flatpack ? _state.FlatpackMultiplier : 1f;

        foreach (var (mat, baseAmount) in entry.Materials.OrderBy(kv => kv.Key))
        {
            var raw = (int) MathF.Ceiling(baseAmount * mult);
            var line = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, HorizontalExpand = true };
            line.AddChild(MakeMaterialIcon(mat, 18));
            line.AddChild(new Label { Text = MatLine(mat, raw), HorizontalExpand = true, Margin = new Thickness(4, 0, 0, 0), StyleClasses = { "LabelSubText" } });
            line.AddChild(new Label { Text = $"${SheetCost(mat, raw)}", StyleClasses = { "LabelSubText" } });
            detail.AddChild(line);
        }

        var worth = ItemWorth(entry, item.Flatpack);
        foreach (var fee in FeesFor(entry.RecipeId, item.Flatpack))
        {
            // For a percent fee show the rate and what it works out to on this item, e.g. "Research Fee (10%)".
            var label = fee.Type == RequisitionFeeType.Percent ? $"{fee.Name} ({fee.Price}%)" : fee.Name;
            var line = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, HorizontalExpand = true };
            line.AddChild(new Label { Text = label, HorizontalExpand = true, StyleClasses = { "LabelSubText" } });
            line.AddChild(new Label { Text = $"${fee.AmountFor(worth, 1)}", StyleClasses = { "LabelSubText" } });
            detail.AddChild(line);
        }

        return detail;
    }

    private void RebuildTotals()
    {
        BreakdownContainer.RemoveAllChildren();

        var need = new Dictionary<string, int>();
        var feeAgg = new Dictionary<string, (string Name, bool Percent, int Rate, int Count, int Total)>();
        foreach (var item in _cart)
        {
            var entry = _state.Catalogue.FirstOrDefault(e => e.RecipeId == item.RecipeId);
            if (entry == null)
                continue;

            var qty = Math.Max(1, item.Quantity);
            var mult = item.Flatpack ? _state.FlatpackMultiplier : 1f;
            var worth = 0;
            foreach (var (mat, baseAmount) in entry.Materials)
            {
                var raw = (int) MathF.Ceiling(baseAmount * mult) * qty;
                need[mat] = need.GetValueOrDefault(mat) + raw;
                worth += SheetCost(mat, raw);
            }

            foreach (var fee in FeesFor(item.RecipeId, item.Flatpack))
            {
                var prev = feeAgg.GetValueOrDefault(fee.Id);
                feeAgg[fee.Id] = (fee.Name, fee.Type == RequisitionFeeType.Percent, fee.Price, prev.Count + qty, prev.Total + fee.AmountFor(worth, qty));
            }
        }

        // Stock readout (silo-derived), decremented by cart usage.
        StockContainer.RemoveAllChildren();
        if (_state.Stock.Count == 0)
        {
            StockContainer.AddChild(new Label { Text = Loc.GetString("requisitions-stock-none"), StyleClasses = { "LabelSubText" } });
        }
        else
        {
            foreach (var (mat, have) in _state.Stock.OrderBy(kv => kv.Key))
            {
                var used = need.GetValueOrDefault(mat);
                var cell = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, HorizontalExpand = true, Margin = new Thickness(0, 0, 10, 0) };
                cell.AddChild(MakeMaterialIcon(mat, 18));
                var text = MatLine(mat, have - used);
                if (used > 0)
                    text += "  " + Loc.GetString("requisitions-stock-used", ("used", SheetOnly(mat, used)));
                cell.AddChild(new Label { Text = text, HorizontalExpand = true, Margin = new Thickness(4, 0, 0, 0), StyleClasses = { "LabelSubText" }, ClipText = true });
                StockContainer.AddChild(cell);
            }
        }

        var red = Color.FromHex("#e03b3b");
        var materialTotal = 0;
        var anyShort = false;
        foreach (var (mat, qty) in need.OrderBy(kv => kv.Key))
        {
            // The customer's inserted sheets cover part of the need, lowering the billed amount.
            var cover = Math.Min(_state.Contributed.GetValueOrDefault(mat), qty);
            var cost = SheetCost(mat, qty - cover);
            materialTotal += cost;

            // Short when what the silo must still supply exceeds its stock. Add silo materials, or have the
            // customer contribute more, and it clears.
            var isShort = qty - cover > _state.Stock.GetValueOrDefault(mat);
            if (isShort)
                anyShort = true;

            var text = MatLine(mat, qty);
            if (cover > 0)
                text += "  (−" + MatLine(mat, cover) + ")";

            var line = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, HorizontalExpand = true };
            line.AddChild(MakeMaterialIcon(mat, 18));
            var nameLabel = new Label { Text = text, HorizontalExpand = true, Margin = new Thickness(4, 0, 0, 0) };
            var costLabel = new Label { Text = $"${cost}" };
            if (isShort)
            {
                nameLabel.FontColorOverride = red;
                costLabel.FontColorOverride = red;
            }
            line.AddChild(nameLabel);
            line.AddChild(costLabel);
            BreakdownContainer.AddChild(line);
        }

        var feeTotal = 0;
        foreach (var (_, fee) in feeAgg)
        {
            feeTotal += fee.Total;
            // Both read "Name (amount) (count)": percent shows the rate, flat shows the per-unit charge.
            var rate = fee.Percent ? $"{fee.Rate}%" : $"${fee.Rate}";
            var text = $"{fee.Name} ({rate}) ({fee.Count})";
            var line = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, HorizontalExpand = true };
            line.AddChild(new Label { Text = text, HorizontalExpand = true, Margin = new Thickness(22, 0, 0, 0) });
            line.AddChild(new Label { Text = $"${fee.Total}" });
            BreakdownContainer.AddChild(line);
        }

        var total = materialTotal + feeTotal;

        // Sync the editable final-price field to the calculated total, but ONLY when that total actually changed.
        // RebuildTotals runs on every state refresh, including background ones that don't touch the price (ejecting
        // stored boards, toggling the detailed-invoice flag, a second viewer opening the console). Comparing against
        // the last total means those refreshes leave a manually-typed price alone, while anything that genuinely
        // alters the price (cart edit, flatpack toggle, a contributed-material or fee/price change) snaps the field
        // back to the fresh calculated figure — discarding the manual edit, as intended.
        if (total != _calculatedTotal)
        {
            _calculatedTotal = total;
            FinalPriceEdit.Text = total.ToString();
        }

        // Locked while a checkout is printing, matching the rest of the tab.
        FinalPriceEdit.Editable = !_state.Processing;

        // Divider, then Material cost / Fees on the left and the Total on the right. Material cost turns red
        // while the silo can't cover the order.
        BreakdownContainer.AddChild(new PanelContainer { StyleClasses = { "LowDivider" }, Margin = new Thickness(0, 4, 0, 4) });
        var summary = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, HorizontalExpand = true };
        var matSummary = new Label
        {
            Text = Loc.GetString("requisitions-summary-material") + $" ${materialTotal}",
            StyleClasses = { "LabelSubText" },
        };
        if (anyShort)
            matSummary.FontColorOverride = red;
        summary.AddChild(matSummary);
        summary.AddChild(new Label
        {
            Text = "    " + Loc.GetString("requisitions-summary-fees") + $" ${feeTotal}",
            StyleClasses = { "LabelSubText" },
        });
        summary.AddChild(new Control { HorizontalExpand = true });
        summary.AddChild(new Label
        {
            Text = Loc.GetString("requisitions-summary-total") + $" ${total}",
            StyleClasses = { "LabelKeyText" },
        });
        BreakdownContainer.AddChild(summary);

        CheckoutButton.Disabled = _state.Processing || _cart.Count == 0;
        CancelButton.Disabled = _state.Processing;
    }

    private void Checkout()
    {
        // Only treat the field as an override when it's a valid price that differs from the calculated total.
        int? overridePrice = null;
        if (int.TryParse(FinalPriceEdit.Text, out var p) && p >= 0 && p != _calculatedTotal)
            overridePrice = p;

        OnCheckout?.Invoke(new List<RequisitionCartItem>(_cart), PrintInvoiceCheck.Pressed, InvoiceTitle.Text, overridePrice);
        _cart.Clear();
        _expanded.Clear();
        CartChanged();
    }

    #endregion

    #region Config

    private void RebuildConfig()
    {
        DetailedInvoiceCheck.Pressed = _state.DetailedInvoice;

        EjectButton.Visible = _state.PendingFlatpacks > 0;
        EjectButton.Text = Loc.GetString("requisitions-config-eject", ("count", _state.PendingFlatpacks));

        // Raw materials
        MaterialContainer.RemoveAllChildren();
        foreach (var (mat, price) in _state.MaterialPrices.OrderBy(kv => MatName(kv.Key)))
        {
            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, HorizontalExpand = true };
            row.AddChild(MakeMaterialIcon(mat, 20));
            row.AddChild(new Label { Text = MatName(mat), HorizontalExpand = true, Margin = new Thickness(4, 0, 0, 0) });
            var edit = new LineEdit { Text = price.ToString(), MinWidth = 70 };
            var matId = mat;
            edit.OnTextEntered += a =>
            {
                if (int.TryParse(a.Text, out var p))
                    OnSetMaterialPrice?.Invoke(matId, p);
            };
            row.AddChild(edit);
            MaterialContainer.AddChild(row);
        }

        // Fees
        FeeContainer.RemoveAllChildren();
        foreach (var fee in _state.Fees)
        {
            var isFlatpack = fee.Scope == RequisitionFeeScope.Flatpack;
            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, HorizontalExpand = true };

            var nameEdit = new LineEdit { Text = fee.Name, HorizontalExpand = true, Editable = !isFlatpack };
            var capturedName = fee;
            nameEdit.OnTextEntered += a =>
            {
                var updated = Clone(capturedName);
                updated.Name = a.Text;
                OnSetFee?.Invoke(updated);
            };
            row.AddChild(nameEdit);

            row.AddChild(new Label { Text = AppliesText(fee), StyleClasses = { "LabelSubText" }, Margin = new Thickness(6, 0, 6, 0) });

            var priceEdit = new LineEdit { Text = fee.Price.ToString(), MinWidth = 70 };
            var capturedPrice = fee;
            priceEdit.OnTextEntered += a =>
            {
                if (!int.TryParse(a.Text, out var p))
                    return;
                var updated = Clone(capturedPrice);
                updated.Price = p;
                OnSetFee?.Invoke(updated);
            };
            row.AddChild(priceEdit);

            // Flat vs percent dropdown. A percent fee adds that % of the item's material value.
            var typeDropdown = new OptionButton { MinWidth = 90, Margin = new Thickness(6, 0, 0, 0), ToolTip = Loc.GetString("requisitions-fee-type-tooltip") };
            typeDropdown.AddItem(Loc.GetString("requisitions-fee-type-flat"), (int) RequisitionFeeType.Flat);
            typeDropdown.AddItem(Loc.GetString("requisitions-fee-type-percent"), (int) RequisitionFeeType.Percent);
            typeDropdown.SelectId((int) fee.Type);
            var capturedType = fee;
            typeDropdown.OnItemSelected += a =>
            {
                typeDropdown.SelectId(a.Id);
                var updated = Clone(capturedType);
                updated.Type = (RequisitionFeeType) a.Id;
                OnSetFee?.Invoke(updated);
            };
            row.AddChild(typeDropdown);

            if (!isFlatpack)
            {
                var assign = new Button { Text = Loc.GetString("requisitions-assign-button"), Margin = new Thickness(6, 0, 0, 0) };
                var capturedAssign = fee;
                assign.OnPressed += _ => OpenAssignDialog(capturedAssign);
                row.AddChild(assign);

                var remove = new Button { Text = "✕", Margin = new Thickness(6, 0, 0, 0), StyleClasses = { "ButtonColorRed" } };
                var feeId = fee.Id;
                remove.OnPressed += _ => OnRemoveFee?.Invoke(feeId);
                row.AddChild(remove);
            }

            FeeContainer.AddChild(row);
        }

        // Links — only show machines we can actually link (in range) or ones already linked (so you can unlink).
        LinkContainer.RemoveAllChildren();
        var shownLinks = _state.Linkable.Where(l => l.Linked || l.InRange).ToList();
        if (shownLinks.Count == 0)
            LinkContainer.AddChild(new Label { Text = Loc.GetString("requisitions-links-none"), StyleClasses = { "LabelSubText" } });

        foreach (var link in shownLinks)
        {
            var status = link.Linked ? Loc.GetString("requisitions-link-linked") : Loc.GetString("requisitions-link-inrange");
            var btn = new Button { Text = $"{link.Label}  —  {status}", HorizontalExpand = true, Margin = new Thickness(0, 1) };
            var machine = link.Machine;
            btn.OnPressed += _ => OnToggleLink?.Invoke(machine);
            LinkContainer.AddChild(btn);
        }
    }

    private void AddFee()
    {
        // Add a blank fee; the operator then renames it and assigns items via the row controls.
        OnSetFee?.Invoke(new RequisitionFee
        {
            Id = "fee_" + _state.Fees.Count + "_" + (_state.Catalogue.Count + _cart.Count),
            Name = Loc.GetString("requisitions-new-fee-name"),
            Price = 0,
            Scope = RequisitionFeeScope.All,
        });
    }

    private void OpenAssignDialog(RequisitionFee fee)
    {
        var win = new DefaultWindow
        {
            Title = Loc.GetString("requisitions-dialog-assign-title", ("name", fee.Name)),
            MinSize = new Vector2(340, 420),
        };

        var vbox = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, HorizontalExpand = true, VerticalExpand = true };
        var all = new CheckBox { Text = Loc.GetString("requisitions-dialog-assign-all"), Pressed = fee.Scope == RequisitionFeeScope.All };
        vbox.AddChild(all);

        var search = new LineEdit { PlaceHolder = Loc.GetString("requisitions-search-placeholder"), Margin = new Thickness(0, 4, 0, 4) };
        vbox.AddChild(search);

        var checks = new Dictionary<string, CheckBox>();
        var rows = new List<(BoxContainer Row, string Name)>();
        var scroll = new ScrollContainer { VerticalExpand = true, HScrollEnabled = false };
        var list = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical };
        foreach (var entry in _state.Catalogue)
        {
            var itemRow = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, HorizontalExpand = true };
            itemRow.AddChild(MakeIcon(entry.Result, 24));
            var cb = new CheckBox
            {
                Text = entry.Name,
                Pressed = fee.Scope == RequisitionFeeScope.Specific && fee.Recipes.Contains(entry.RecipeId),
                Margin = new Thickness(4, 0, 0, 0),
            };
            checks[entry.RecipeId] = cb;
            itemRow.AddChild(cb);
            list.AddChild(itemRow);
            rows.Add((itemRow, entry.Name));
        }
        scroll.AddChild(list);
        vbox.AddChild(scroll);

        // Filter the list as the operator types; hiding rows preserves each checkbox's state.
        search.OnTextChanged += a =>
        {
            var filter = a.Text.Trim();
            foreach (var (row, name) in rows)
                row.Visible = filter.Length == 0 || name.Contains(filter, StringComparison.OrdinalIgnoreCase);
        };

        var save = new Button { Text = Loc.GetString("requisitions-save"), Margin = new Thickness(0, 6, 0, 0) };
        save.OnPressed += _ =>
        {
            var updated = Clone(fee);
            if (all.Pressed)
            {
                updated.Scope = RequisitionFeeScope.All;
                updated.Recipes = new HashSet<ProtoId<LatheRecipePrototype>>();
            }
            else
            {
                updated.Scope = RequisitionFeeScope.Specific;
                updated.Recipes = checks.Where(kv => kv.Value.Pressed)
                    .Select(kv => (ProtoId<LatheRecipePrototype>) kv.Key)
                    .ToHashSet();
            }
            OnSetFee?.Invoke(updated);
            win.Close();
        };
        vbox.AddChild(save);

        win.Contents.AddChild(vbox);
        win.OpenCentered();
    }

    private static RequisitionFee Clone(RequisitionFee fee) => new()
    {
        Id = fee.Id,
        Name = fee.Name,
        Price = fee.Price,
        Type = fee.Type,
        Scope = fee.Scope,
        Recipes = new HashSet<ProtoId<LatheRecipePrototype>>(fee.Recipes),
    };

    private string AppliesText(RequisitionFee fee) => fee.Scope switch
    {
        RequisitionFeeScope.All => Loc.GetString("requisitions-applies-all"),
        RequisitionFeeScope.Flatpack => Loc.GetString("requisitions-applies-flatpack"),
        _ => fee.Recipes.Count == 0
            ? Loc.GetString("requisitions-applies-none")
            : Loc.GetString("requisitions-applies-count", ("count", fee.Recipes.Count)),
    };

    #endregion

    #region Pricing helpers

    private int MaterialPrice(string mat) => _state.MaterialPrices.TryGetValue(mat, out var p) ? p : 0;

    private string MatName(string mat)
    {
        if (_state.MaterialNames.TryGetValue(mat, out var n))
            return n;
        return _proto.TryIndex<MaterialPrototype>(mat, out var m) ? Loc.GetString(m.Name) : mat;
    }

    private float SheetVolume(string matId) =>
        _proto.TryIndex<MaterialPrototype>(matId, out var m) ? Math.Max(1, _materialStorage.GetSheetVolume(m)) : 1;

    /// <summary>Just the amount and unit, e.g. "12.5 sheets" (or "12.5 ingots" for ingot materials).</summary>
    private string SheetOnly(string matId, int rawAmount)
    {
        var sheets = rawAmount / SheetVolume(matId);
        var unit = _proto.TryIndex<MaterialPrototype>(matId, out var m) ? Loc.GetString(m.Unit) : matId;
        return Loc.GetString("requisitions-material-sheets", ("amount", MathF.Round(sheets, 2)), ("unit", unit));
    }

    /// <summary>Named material line, amount first to match the invoice, e.g. "12.5 Steel sheets".</summary>
    private string MatLine(string matId, int rawAmount)
    {
        var amount = MathF.Round(rawAmount / SheetVolume(matId), 2);
        var unit = _proto.TryIndex<MaterialPrototype>(matId, out var m) ? Loc.GetString(m.Unit) : matId;
        return $"{amount} {MatName(matId)} {unit}";
    }

    private int SheetCost(string matId, int rawAmount)
    {
        if (rawAmount <= 0)
            return 0;
        return (int) MathF.Round(rawAmount / SheetVolume(matId) * MaterialPrice(matId));
    }

    private IEnumerable<RequisitionFee> FeesFor(string recipeId, bool flatpack)
    {
        foreach (var fee in _state.Fees)
        {
            var applies = fee.Scope switch
            {
                RequisitionFeeScope.Flatpack => flatpack,
                RequisitionFeeScope.All => true,
                RequisitionFeeScope.Specific => fee.Recipes.Contains(recipeId),
                _ => false,
            };
            if (applies)
                yield return fee;
        }
    }

    /// <summary>Full material value of one unit (no contribution discount) — the base for percent fees.</summary>
    private int ItemWorth(RequisitionCatalogueEntry entry, bool flatpack)
    {
        var mult = flatpack ? _state.FlatpackMultiplier : 1f;
        var worth = 0;
        foreach (var (mat, baseAmount) in entry.Materials)
            worth += SheetCost(mat, (int) MathF.Ceiling(baseAmount * mult));
        return worth;
    }

    private int ItemCost(RequisitionCatalogueEntry entry, bool flatpack)
    {
        var worth = ItemWorth(entry, flatpack);
        var cost = worth;
        foreach (var fee in FeesFor(entry.RecipeId, flatpack))
            cost += fee.AmountFor(worth, 1);
        return cost;
    }

    #endregion
}
