using Content.Client.Computer;
using Content.Client.UserInterface.Controls;
using Content.Shared.Shuttles.BUIStates;
using Content.Shared.Shuttles.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using System.Numerics;
using System.Text;

namespace Content.Client.Shuttles.UI;

[GenerateTypedNameReferences]
public sealed partial class IFFConsoleWindow : FancyWindow,
    IComputerWindow<IFFConsoleBoundUserInterfaceState>
{
    private const int SignatureHexLength = 6;
    private readonly ButtonGroup _showIFFButtonGroup = new();
    private readonly ButtonGroup _showVesselButtonGroup = new();
    private readonly StyleBoxFlat _swatchStyleBox = new();
    private bool _canEditColor;
    private bool _canEditDesignation;
    private bool _designationOptionsLoaded;
    private bool _suppressDesignationEvent;
    private bool _updatingColorControls;
    public event Action<bool>? ShowIFF;
    public event Action<bool>? ShowVessel;
    public event Action<string>? OnSetColor;
    public event Action<IFFDesignation>? SetDesignation;

    private Color _color;

    public IFFConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        ShowIFFOffButton.Group = _showIFFButtonGroup;
        ShowIFFOnButton.Group = _showIFFButtonGroup;
        ShowIFFOnButton.OnPressed += args => ShowIFFPressed(true);
        ShowIFFOffButton.OnPressed += args => ShowIFFPressed(false);

        ShowVesselOffButton.Group = _showVesselButtonGroup;
        ShowVesselOnButton.Group = _showVesselButtonGroup;
        ShowVesselOnButton.OnPressed += args => ShowVesselPressed(true);
        ShowVesselOffButton.OnPressed += args => ShowVesselPressed(false);

        SignatureColorSwatch.PanelOverride = _swatchStyleBox;
        DesignationOptionButton.OnItemSelected += args => OnDesignationSelected(args.Id);

        ApplyColorButton.OnPressed += _ => ApplySignatureColor();
        SignatureColorLineEdit.OnTextEntered += args => { OnColorTextChanged(args.Text); ApplySignatureColor(); };
        SignatureColorLineEdit.OnTextChanged += args => OnColorTextChanged(args.Text);

        HueField.OnTextChanged += _ => UpdateSliderFromField(HueField, HueSlider);
        ValueField.OnTextChanged += _ => UpdateSliderFromField(ValueField, ValueSlider);
        SaturationField.OnTextChanged += _ => UpdateSliderFromField(SaturationField, SaturationSlider);

        HueSlider.OnValueChanged += _ => UpdateColorFromHSV();
        ValueSlider.OnValueChanged += _ => UpdateColorFromHSV();
        SaturationSlider.OnValueChanged += _ => UpdateColorFromHSV();
    }

    private void ShowIFFPressed(bool pressed)
    {
        ShowIFF?.Invoke(pressed);
    }

    private void ShowVesselPressed(bool pressed)
    {
        ShowVessel?.Invoke(pressed);
    }

    private void ApplySignatureColor()
    {
        OnSetColor?.Invoke(_color.ToHexNoAlpha());
    }

    private void EnsureDesignationOptions()
    {
        if (_designationOptionsLoaded)
            return;

        DesignationOptionButton.Clear();
        DesignationOptionButton.AddItem(Loc.GetString("iff-console-designation-ship"), (int)IFFDesignation.Ship);
        DesignationOptionButton.AddItem(Loc.GetString("iff-console-designation-station"), (int)IFFDesignation.Station);
        _designationOptionsLoaded = true;
    }

    private void OnDesignationSelected(int id)
    {
        if (_suppressDesignationEvent)
            return;

        if (!_canEditDesignation)
            return;

        if (id < byte.MinValue || id > byte.MaxValue)
            return;

        var designationId = (byte)id;
        if (!Enum.IsDefined(typeof(IFFDesignation), designationId))
            return;

        DesignationOptionButton.SelectId(id);
        SetDesignation?.Invoke((IFFDesignation)designationId);
    }

    private void OnColorTextChanged(string text)
    {
        var sanitized = SanitizeColorHex(text);

        if (SignatureColorLineEdit.Text != sanitized)
        {
            SignatureColorLineEdit.Text = sanitized;
            SignatureColorLineEdit.CursorPosition = sanitized.Length;
        }
        if (sanitized.Length == SignatureHexLength)
            UpdateHSVFromHex(sanitized);
    }

    private static string SanitizeColorHex(string? value)
    {
        if (string.IsNullOrWhiteSpace(value))
            return string.Empty;

        var result = new StringBuilder(SignatureHexLength);

        foreach (var ch in value)
        {
            if (result.Length >= SignatureHexLength)
                break;

            if (Uri.IsHexDigit(ch))
                result.Append(char.ToUpperInvariant(ch));
        }

        return result.ToString();
    }

    private void UpdateApplyButtonState()
    {
        ApplyColorButton.Disabled = !_canEditColor || SignatureColorLineEdit.Text.Length != SignatureHexLength;
    }

    public void UpdateState(IFFConsoleBoundUserInterfaceState state)
    {
        if ((state.AllowedFlags & IFFFlags.HideLabel) != 0x0 || (state.AllowedFlags & IFFFlags.Hide) != 0x0)
        {
            ShowIFFOffButton.Disabled = false;
            ShowIFFOnButton.Disabled = false;

            if ((state.Flags & IFFFlags.HideLabel) != 0x0 || (state.Flags & IFFFlags.Hide) != 0x0)
            {
                ShowIFFOffButton.Pressed = true;
            }
            else
            {
                ShowIFFOnButton.Pressed = true;
            }
        }
        else
        {
            ShowIFFOffButton.Disabled = true;
            ShowIFFOnButton.Disabled = true;
        }

        if ((state.AllowedFlags & IFFFlags.Hide) != 0x0)
        {
            ShowVesselOffButton.Disabled = false;
            ShowVesselOnButton.Disabled = false;

            if ((state.Flags & IFFFlags.Hide) != 0x0)
            {
                ShowVesselOffButton.Pressed = true;
            }
            else
            {
                ShowVesselOnButton.Pressed = true;
            }
        }
        else
        {
            ShowVesselOffButton.Disabled = true;
            ShowVesselOnButton.Disabled = true;
        }

        _canEditColor = state.ColorEditable;
        UpdateApplyButtonState();
        SignatureColorLineEdit.Editable = state.ColorEditable;

        _canEditDesignation = state.DesignationEditable;
        EnsureDesignationOptions();
        DesignationOptionButton.Disabled = !_canEditDesignation;
        _suppressDesignationEvent = true;
        DesignationOptionButton.SelectId((int)state.Designation);
        _suppressDesignationEvent = false;

        SetColor(state.SignatureColor);
        UpdateApplyButtonState();
    }

    private void SetColor(Color color)
    {
        if (_updatingColorControls)
            return;

        _updatingColorControls = true;
        _color = color;

        SignatureColorLineEdit.Text = color.ToHexNoAlpha().TrimStart('#');

        var hsv = Color.ToHsv(color);

        ValueSlider.Value = MathF.Round(hsv[2] * 255f);
        if (ValueSlider.Value > 0.001f)
        {
            SaturationSlider.Value = MathF.Round(hsv[1] * 255f);

            if (SaturationSlider.Value > 0.001f)
                if (HueSlider.Value <= 255f - 0.001f || hsv[0] > 0.001f)
                    HueSlider.Value = MathF.Round(hsv[0] * 255f);
        }

        HueField.Text = $"{HueSlider.Value:0}";
        SaturationField.Text = $"{SaturationSlider.Value:0}";
        ValueField.Text = $"{ValueSlider.Value:0}";

        _swatchStyleBox.BackgroundColor = color;

        UpdateApplyButtonState();
        _updatingColorControls = false;
    }

    private void UpdateColorFromHSV()
    {
        if (_updatingColorControls)
            return;

        var h = HueSlider.Value / 255f;
        var s = SaturationSlider.Value / 255f;
        var v = ValueSlider.Value / 255f;

        var color = Color.FromHsv(new Vector4(h, s, v, 1f));
        SetColor(color);
    }

    private void UpdateHSVFromHex(string hex)
    {
        if (_updatingColorControls)
            return;

        var color = Color.FromHex($"#{hex}");
        SetColor(color);
    }

    private void UpdateSliderFromField(LineEdit field, Slider slider)
    {
        if (!int.TryParse(field.Text, out var value))
            return;

        slider.Value = Math.Clamp(value, slider.MinValue, slider.MaxValue);
        UpdateColorFromHSV();
    }
}
