using System.Numerics;
using Content.Client.Shuttles.Systems;
using Content.Client.Stylesheets;
using Content.Shared.Sectors.Prototypes;
using Content.Shared.Shuttles.BUIStates;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Physics.Components;
using Content.Shared.Shuttles.Components;
using Content.Shared.Sectors;
using Robust.Shared.Prototypes;

namespace Content.Client.Shuttles.UI;

[GenerateTypedNameReferences]
public sealed partial class NavScreen : BoxContainer
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypes = default!;
    private SharedTransformSystem _xformSystem;
    private SharedSectorSystem _sectorSystem;
    private readonly ShuttleSystem _shuttles;

    private EntityUid? _consoleEntity; // Entity of controlling console
    private EntityUid? _shuttleEntity;
    private Dictionary<SpaceSector, string> _sectorHazards = new();

    public Action<ShuttleDampingMode>? OnDampingModeChanged;

    public RadioOptions<int> DampingModeSelector;

    public NavScreen()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _xformSystem = _entManager.System<SharedTransformSystem>();
        _sectorSystem = _entManager.System<SharedSectorSystem>();
        _shuttles = _entManager.System<ShuttleSystem>();

        IFFToggle.OnToggled += OnIFFTogglePressed;
        IFFToggle.Pressed = NavRadar.ShowIFF;

        DockToggle.OnToggled += OnDockTogglePressed;
        DockToggle.Pressed = NavRadar.ShowDocks;

        DampingModeSelector = new RadioOptions<int>(RadioOptionsLayout.Horizontal)
        {
            FirstButtonStyle = StyleClass.ButtonOpenRight,
            ButtonStyle = StyleClass.ButtonOpenBoth,
            LastButtonStyle = StyleClass.ButtonOpenLeft,
            HorizontalExpand = true,
        };
        DampingModeSelector.AddItem(Loc.GetString("shuttle-console-damping-cruise"), (int)ShuttleDampingMode.Cruise);
        DampingModeSelector.AddItem(Loc.GetString("shuttle-console-damping-normal"), (int)ShuttleDampingMode.Normal);
        DampingModeSelector.AddItem(Loc.GetString("shuttle-console-damping-anchor"), (int)ShuttleDampingMode.Anchor);
        DampingModeSelector.OnItemSelected += OnDampingSelected;

        DampingModeSelectorContainer.AddChild(DampingModeSelector);

        FilterStation.Pressed = NavRadar.SortMode.HasFlag(IFFSortMode.Station);
        FilterShip.Pressed = NavRadar.SortMode.HasFlag(IFFSortMode.Ship);
        FilterOther.Pressed = NavRadar.SortMode.HasFlag(IFFSortMode.Other);

        FilterStation.OnToggled += _ => SetSortModeFlags();
        FilterShip.OnToggled += _ => SetSortModeFlags();
        FilterOther.OnToggled += _ => SetSortModeFlags();
    }

    public void SetShuttle(EntityUid? shuttle)
    {
        _shuttleEntity = shuttle;
    }

    public void SetConsole(EntityUid? console)
    {
        _consoleEntity = console;
        NavRadar.SetConsole(console);
    }

    private void OnIFFTogglePressed(BaseButton.ButtonEventArgs args)
    {
        NavRadar.ShowIFF ^= true;
        args.Button.Pressed = NavRadar.ShowIFF;
    }

    private void OnDockTogglePressed(BaseButton.ButtonEventArgs args)
    {
        NavRadar.ShowDocks ^= true;
        args.Button.Pressed = NavRadar.ShowDocks;
    }

    public void UpdateState(NavInterfaceState scc)
    {
        NavRadar.UpdateState(scc);
        DampingModeSelector.Select((int)scc.DampingMode);
        _sectorHazards = scc.SectorWeatherEvents;
    }

    private string ResolveHazardName(string prototypeId)
    {
        if (_prototypes.TryIndex<SectorWeatherPrototype>(prototypeId, out var weather) &&
            !string.IsNullOrWhiteSpace(weather.Name))
        {
            return Loc.GetString(weather.Name);
        }

        return prototypeId;
    }

    public void SetMatrix(EntityCoordinates? coordinates, Angle? angle)
    {
        _shuttleEntity = coordinates?.EntityId;
        NavRadar.SetMatrix(coordinates, angle);
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        if (!_entManager.TryGetComponent(_shuttleEntity, out TransformComponent? gridXform) ||
            !_entManager.TryGetComponent(_shuttleEntity, out PhysicsComponent? gridBody))
        {
            return;
        }

        var (_, worldRot, worldMatrix) = _xformSystem.GetWorldPositionRotationMatrix(gridXform);
        var worldPos = Vector2.Transform(gridBody.LocalCenter, worldMatrix);

        // Get the positive reduced angle.
        var displayRot = -worldRot.Reduced();

        GridName.Text = _shuttles.GetIFFLabel(_shuttleEntity!.Value, true);

        GridPosition.Text = Loc.GetString("shuttle-console-position-value",
            ("X", $"{worldPos.X:0.0}"),
            ("Y", $"{worldPos.Y:0.0}"));
        var currentSector = _sectorSystem.GetSector(worldPos);
        GridSector.Text = Loc.GetString("shuttle-console-sector-value",
            ("sector", _sectorSystem.GetSectorName(currentSector)));

        if (_sectorHazards.TryGetValue(currentSector, out var hazardId))
        {
            GridHazardWeather.Text = Loc.GetString("shuttle-console-hazard-event-single", ("event", ResolveHazardName(hazardId)));
            GridHazardWeather.Modulate = Color.OrangeRed;
        }
        else
        {
            GridHazardWeather.Text = Loc.GetString("shuttle-console-hazard-event-none");
            GridHazardWeather.Modulate = Color.White;
        }

        GridOrientation.Text = Loc.GetString("shuttle-console-orientation-value",
            ("angle", $"{displayRot.Degrees:0.0}"));

        var gridVelocity = gridBody.LinearVelocity;
        gridVelocity = displayRot.RotateVec(gridVelocity);
        // Get linear velocity relative to the console entity
        GridLinearVelocity.Text = Loc.GetString("shuttle-console-linear-velocity-value",
            ("X", $"{gridVelocity.X + 10f * float.Epsilon:0.0}"),
            ("Y", $"{gridVelocity.Y + 10f * float.Epsilon:0.0}"));
        GridAngularVelocity.Text = Loc.GetString("shuttle-console-angular-velocity-value",
            ("angularVelocity", $"{-MathHelper.RadiansToDegrees(gridBody.AngularVelocity) + 10f * float.Epsilon:0.0}"));
    }

    private void OnDampingSelected(RadioOptionItemSelectedEventArgs<int> args)
    {
        DampingModeSelector.Select(args.Id);
        OnDampingModeChanged?.Invoke((ShuttleDampingMode)args.Id);
    }

    private void SetSortModeFlags()
    {
        NavRadar.SortMode =
            (FilterStation.Pressed ? IFFSortMode.Station : 0)
            | (FilterShip.Pressed ? IFFSortMode.Ship : 0)
            | (FilterOther.Pressed ? IFFSortMode.Other : 0);
    }
}
