using Content.Client.Message;
using Content.Client.MessageBoard.UI;
using Content.Client.Store.Ui;
using Content.Shared._Persistence14.Rumors.Prototypes;
using Content.Shared.Cargo.Components;
using Content.Shared.CrewAssignments;
using Content.Shared.CrewAssignments.Prototypes;
using Content.Shared.CrewMetaRecords;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using static Robust.Client.UserInterface.Controls.MenuBar;

namespace Content.Client.CrewAssignments.UI;

[GenerateTypedNameReferences]
public sealed partial class JobNetMenu : DefaultWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    private bool _rumorRewardsBuilt = false;
    public TimeSpan UntilNextPay = TimeSpan.Zero;
    public TimeSpan UntilNextPrec = TimeSpan.Zero;
    public TimeSpan UntilNextRumor = TimeSpan.Zero;
    public SpriteSystem? _spriteSystem;
    public JobNetBoundUserInterface? Owner;
    public Action<string>? OnLabelButtonPressed;
    public JobNetMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        MasterTabContainer.SetTabTitle(0, "Job Network");
        MasterTabContainer.SetTabTitle(1, "History");
        MasterTabContainer.SetTabTitle(2, "Sector");
        MasterTabContainer.SetTabTitle(3, "Upgrades");
        MasterTabContainer.SetTabTitle(4, "Rumors");
        MasterTabContainer.SetTabTitle(5, "Messages");
    }

    public void UpdateState(JobNetUpdateState state)
    {
        List<TradeStationComponent> stations = new();
        var query = _entityManager.EntityQueryEnumerator<TradeStationComponent>();
        while (query.MoveNext(out var uid, out var station))
        {
            stations.Add(station);
        }

        if (state.SpendAuth)
        {
            SLDetails.Visible = true;
            SpendingLabel.Text = $"${state.Spent}/${state.Spendable}";
        }
        else
        {
            SLDetails.Visible = false;
        }
        AccountBalanceLabel.Text = $"${state.Balance}";
        var dependencies = IoCManager.Instance!;
        var localPlayer = dependencies.Resolve<IPlayerManager>().LocalEntity;
        PossibleJobs.Clear();
        PossibleJobs.AddItem("Off Duty", 0);
        RumorTaxLabel.Text = $"{state.RumorTax.ToString()}% of rumor money rewards paid to your employer.";
        if (state.Stations != null)
        {
            int ind = 1;
            foreach (var kv in state.Stations)
            {

                PossibleJobs.AddItem(kv.Value, kv.Key);
                if (kv.Key == state.SelectedStation)
                    PossibleJobs.Select(ind);
                ind++;
            }
        }
        if (state.AssignmentName != null)
        {
            CSLabel.Text = state.AssignmentName;
            AssignmentDetails.Visible = true;
        }
        else
        {
            CSLabel.Text = "Off Duty";
            AssignmentDetails.Visible = false;
        }
        if (state.Wage != null)
        {
            WageLabel.Text = "$" + state.Wage.ToString();
        }
        else
        {
            WageLabel.Text = "$0";
        }
        if (state.RemainingMinutes != null)
        {
            UntilNextPay = state.RemainingMinutes.Value;
            TimeLabel.Text = UntilNextPay.ToString("mm\\:ss");
        }
        else
        {
            TimeLabel.Text = "Invalid";
        }
        CurrentObjectives.RemoveAllChildren();
        foreach (var objective in state.CurrentObjectives)
        {
            if (!objective.Visible) continue;
            WorldObjectiveEntryFragment entry = new(objective.Title, objective.Description, objective.Reward, null, null);
            CurrentObjectives.AddChild(entry);
        }
        CompletedObjectives.RemoveAllChildren();
        foreach (var objective in state.CompletedObjectives)
        {
            if (!objective.Visible) continue;
            WorldObjectiveEntryFragment entry = new(objective.Title, objective.Description, objective.Reward, objective.CompletedTime, objective.CompletedDescription);
            CompletedObjectives.AddChild(entry);
        }

        CodexContainer.RemoveAllChildren();

        var charName = "";
        if (localPlayer != null)
            charName = _entityManager.GetComponent<MetaDataComponent>(localPlayer.Value).EntityName;
        int totalNum = 0;
        int lockedNum = 0;
        foreach (var codexEntry in state.CodexEntries)
        {
            totalNum++;
            Button button = new();
            if (!codexEntry.Visible && !codexEntry.Whitelist.Contains(charName))
            {
                lockedNum++;
                button.Disabled = true;
            }
            button.Text = codexEntry.Title;
            button.OnPressed += _ => OnSelectCodex(codexEntry.Title, codexEntry.Description);
            CodexContainer.AddChild(button);
        }
        UnlockedNumberLabel.Text = $"[head=3][color=yellow]{totalNum - lockedNum}/{totalNum}[/color] Codex Entries Unlocked[/head]";
        _prototypeManager.Resolve(state.Level, out var levelProto);
        if (levelProto != null)
        {
            NetworkLevelPrototype? nextLevelProto = null;

            if (levelProto.Next != null)
                _prototypeManager.Resolve(levelProto.Next, out nextLevelProto);

            CurrentLevelLabel.Text = levelProto.Name;
            string levelDesc = $"Owned Tile Limit:[color=yellow]{levelProto.TileLimit}[/color]";
            CurrentBenefitsLabel.SetMarkup(levelDesc);
            string nextLevelDesc;
            if (nextLevelProto == null)
            {
                NextLevelLabel.Text = "Max Level Attained";
                nextLevelDesc = "[color=green]Maximum Level Attained[/color]";
                LevelPurchaseButton.Visible = false;
            }
            else
            {
                NextLevelLabel.Text = nextLevelProto.Name;
                nextLevelDesc = $"Owned Tile Limit:[color=green]{nextLevelProto.TileLimit}[/color]";
                LevelPurchaseButton.Visible = true;
                LevelPurchaseButton.Text = $"${nextLevelProto.Cost}";
            }
            NextBenefitsLabel.SetMarkup(nextLevelDesc);
        }
        var metaFactions = _prototypeManager.EnumeratePrototypes<MetaFactionPrototype>();
        CurrentGrid.RemoveAllChildren();
        ReputationsGrid.RemoveAllChildren();
        Dictionary<ProtoId<MetaFactionPrototype>, int> reputations = new();
        foreach (var faction in metaFactions)
        {
            int rep = 0;
            if (state.MetaFactionReputations.TryGetValue(faction.ID, out var repVal))
                rep = repVal;
            reputations[faction.ID] = rep;
            ReputationBoxFragment repLabel = new(faction, rep);
            ReputationsGrid.AddChild(repLabel);
        }
        int rind = 0;
        foreach (var rumor in state.Rumors)
        {
            RumorBoxFragment rumorLabel = new(rumor);
            rumorLabel.RumorIndex = rind;
            rind++;
            rumorLabel.CancelBtn.OnPressed += args =>
            {
                if (Owner != null) Owner.CancelRumor(rumorLabel.RumorIndex);
            };
            rumorLabel.TransferBtn.OnPressed += args =>
            {
                if (Owner != null) Owner.TransferRumor(rumorLabel.RumorIndex, rumorLabel.TransferLE.Text);
            };
            CurrentGrid.AddChild(rumorLabel);
        }
        if (state.RumorCooldown != null)
        {
            RumorCooldownLbl.Text = $"Next rumor in:{state.RumorCooldown.Value.ToString("mm\\:ss")}";
            UntilNextRumor = state.RumorCooldown.Value;
        }
        RumorLimitLbl.Text = $"{state.Rumors.Count.ToString()}/4 Available";

        ActiveConversations.RemoveAllChildren();
        if (state.DirectMessages != null && Owner != null)
        {
            foreach (var kv in state.DirectMessages)
            {
                var author = kv.Key;
                var conversation = kv.Value;
                Button convoButton = new Button();
                convoButton.Text = author;
                convoButton.OnPressed += (args) =>
                {
                    if (Owner.ConversationWindow != null)
                    {
                        Owner.ConversationWindow.Dispose();
                    }
                    var conversationWindow = new ConversationWindow(conversation, false, charName, author);
                    Owner.ConversationWindow = conversationWindow;
                    conversationWindow.OpenCentered();
                    conversationWindow.PublicBoardEntriesPC.Visible = false;
                };
                if (Owner.ConversationWindow != null && Owner.ConversationWindow.RecipientName == kv.Key)
                {
                    Owner.ConversationWindow.UpdateEntry(kv.Value);
                }
                ActiveConversations.AddChild(convoButton);
            }
        }
        if (_rumorRewardsBuilt == false)
        {
            _rumorRewardsBuilt = true;
            foreach (var kv in state.RumorRewards)
            {
                var faction = kv.Key;
                var factionProto = _prototypeManager.Index(faction);
                var rewards = kv.Value;
                var rep = reputations[faction];
                RumorRewardPageFragment box = new(this);
                box.FactionId = faction;
                box.Name = factionProto.Name;
                RumorRewardsTC.AddChild(box);
                box.UpdateState(rewards, rep, factionProto);
            }
        }
        else
        {
            foreach (var kv in state.RumorRewards)
            {
                var faction = kv.Key;
                var factionProto = _prototypeManager.Index(faction);
                var rewards = kv.Value;
                var rep = reputations[faction];
                foreach (var box in RumorRewardsTC.Children)
                {
                    if (box is RumorRewardPageFragment page && page.FactionId == faction)
                    {
                        page.UpdateState(rewards, rep, factionProto);
                    }
                }
            }
        }
    }


    private void OnSelectCodex(string title, string description)
    {
        if (Owner == null || Owner.CodexMenu == null) return;
        Owner.CodexMenu.UpdateState(title, description);
        Owner.CodexMenu.OpenCentered();

    }
    private void UpdateSkipButton(float deltaSeconds)
    {
        UntilNextPay -= TimeSpan.FromSeconds(deltaSeconds);
        if (UntilNextPay > TimeSpan.Zero)
        {
            TimeLabel.Text = UntilNextPay.ToString("mm\\:ss");
        }
        UntilNextRumor -= TimeSpan.FromSeconds(deltaSeconds);
        if (UntilNextRumor > TimeSpan.Zero)
        {
            RumorCooldownLbl.Text = UntilNextRumor.ToString("mm\\:ss");
        }
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdateSkipButton(args.DeltaSeconds);
    }

    public void RumorRewardPurchase(ProtoId<RumorRewardPrototype> rewardID, ProtoId<MetaFactionLevelPrototype> levelID, ProtoId<MetaFactionPrototype> factionID)
    {
        if(Owner == null) return;
        Owner.RumorRewardPurchase(rewardID, levelID, factionID);
    }
}
public sealed class JobButton : Button
{
    public int Id;
}
