
using Robust.Client.UserInterface.CustomControls;
using Content.Client.CrewAssignments.AdminUI;
using Content.Shared.CrewAssignments.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Utility;
using System.Collections.Generic;
using System.Linq;
using static Robust.Client.UserInterface.Controls.MenuBar;

namespace Content.Client.CrewAssignments.UI
{
    [GenerateTypedNameReferences]
    sealed partial class PrecursorObjective : PanelContainer
    {
        public PrecursorObjective()
        {
            RobustXamlLoader.Load(this);
        }

    }

}
