using Content.Shared._Persistence14.Rumors.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.CrewAssignments.UI;

[GenerateTypedNameReferences]
public sealed partial class ReputationBoxFragment : PanelContainer
{
    [Dependency] private IPrototypeManager _protoManager = default!;
    public ReputationBoxFragment(MetaFactionPrototype factionProto, int reputation)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        this.PanelOverride = new StyleBoxFlat
        {
            BorderColor = factionProto.Color,
            BorderThickness = new Thickness(5f),
            BackgroundColor = Color.Black
        };
        TitleLabel.Text = factionProto.Name;
        ContentLabel.Text = $"{reputation} Reputation";
    }
}
