using Content.Client.CrewAssignments.BUI;
using Content.Client.Stylesheets;
using Content.Shared._Persistence14.Resonance.Prototypes;
using Content.Shared._Persistence14.Rumors.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;


namespace Content.Client.CrewAssignments.UI;


[GenerateTypedNameReferences]
public sealed partial class ResonanceProductBox : PanelContainer
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private IEntityManager _entMan = default!;

    private ProtoId<ResonanceProductPrototype> _product;
    private StationModificationConsoleBoundUserInterface _owner;
    public ResonanceProductBox(ProtoId<ResonanceProductPrototype> product, int resonance, Dictionary<ProtoId<ResonanceProductPrototype>, int> partialPurchases, StationModificationConsoleBoundUserInterface owner, bool tradeStationClaimed)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _product = product;
        _owner = owner;
        this.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = Color.Black
        };
        var proto = _prototypeManager.Index(product);
        var spriteSystem = _entMan.System<SpriteSystem>();
        Icon.Texture = spriteSystem.Frame0(proto.Icon);
        TitleLabel.Text = proto.Name;
        ContentLabel.Text = proto.Description;
        if(proto.Shared)
        {
            int paid = 0;
            if (partialPurchases.ContainsKey(product))
            {
                paid = partialPurchases[product];
            }
            PurchaseBtn.Text = "Invest $$100";
            if(resonance < 100)
            {
                PurchaseBtn.Disabled = true;
            }
            else
            {
                PurchaseBtn.Disabled = false;
            }
            PartialLabel.Text = $"$${paid} / $${proto.Price}";
        }
        else
        {
            PartialLabel.Text = "";
            PurchaseBtn.Text = $"$${proto.Price}";
            if (resonance < proto.Price)
            {
                PurchaseBtn.Disabled = true;
            }
            else
            {
                PurchaseBtn.Disabled = false;
            }
        }
        if (!tradeStationClaimed) PurchaseBtn.Disabled = true;
        PurchaseBtn.OnPressed += OnPurchase;
    }

    private void OnPurchase(BaseButton.ButtonEventArgs obj)
    {
        _owner.OnResonancePurchase(_product);
    }
}
