using Content.Client.Stylesheets;
using Content.Shared._Persistence14.Rumors.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.CrewAssignments.UI;


[GenerateTypedNameReferences]
public sealed partial class RumorRewardPageFragment : BoxContainer
{
    public string FactionId { get; set; } = string.Empty;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    private JobNetMenu _owner;
    public RumorRewardPageFragment(JobNetMenu jobNetMenu)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _owner = jobNetMenu;
    }

    public void UpdateState(Dictionary<ProtoId<MetaFactionLevelPrototype>, List<ActiveRumorReward>> rewards, int reputation, MetaFactionPrototype factionProto, int balance)
    {
        RemoveAllChildren();

        foreach (var kv in rewards)
        {
            var level = kv.Key;
            var rewardList = kv.Value;
            var levelProto = _prototypeManager.Index(level);
            if (levelProto == null) return;
            var unlocked = false;
            var requirement = factionProto.Levels[kv.Key];
            if (reputation >= requirement) unlocked = true;
            if(rewardList.Count > 0)
            {
                var levelLabel = new Label
                {
                    Text = $"{levelProto.Name}:",
                    StyleClasses = { StyleClass.LabelHeading }

                };
                AddChild(levelLabel);
            }
            foreach (var reward in rewardList)
            {
                var rewardProto = _prototypeManager.Index<RumorRewardPrototype>(reward.Reward);
                RumorRewardBoxFragment rewardBox = new(reward, unlocked, _owner, factionProto, levelProto, balance);
                AddChild(rewardBox);
            }

        }
    }
}
