using Content.Shared._Persistence14.Rumors.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.CrewAssignments.UI;

[GenerateTypedNameReferences]
public sealed partial class RumorRewardBoxFragment : PanelContainer
{
    [Dependency] private IPrototypeManager _protoManager = default!;
    [Dependency] private IEntityManager _entMan = default!;
    public int RumorIndex = 0;
    private JobNetMenu _owner;
    private ProtoId<MetaFactionLevelPrototype> _levelID;
    private ProtoId<MetaFactionPrototype> _factionID;
    private ProtoId<RumorRewardPrototype> _rewardID;
    public RumorRewardBoxFragment(ActiveRumorReward activeRumor, bool unlocked, JobNetMenu owner, MetaFactionPrototype factionProto, MetaFactionLevelPrototype levelProto, int balance)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        this.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = Color.Black
        };
        _levelID = levelProto.ID;
        _factionID = factionProto.ID;
        _rewardID = activeRumor.Reward;
        _owner = owner;
        var spriteSystem = _entMan.System<SpriteSystem>();
        var rewardProto = _protoManager.Index<RumorRewardPrototype>(activeRumor.Reward);
        Icon.Texture = spriteSystem.Frame0(rewardProto.Icon);
        TitleLabel.Text = rewardProto.Name;
        ContentLabel.Text = rewardProto.Description;
        AvailableAtLbl.Text = $"[italic][color=gray]Import to {activeRumor.TradeStationName}";
        if(activeRumor.Purchased)
        {
            PurchaseBtn.Text = $"Purchased";
            PurchaseBtn.Pressed = true;
        }
        else if(unlocked)
        {
            if(balance < rewardProto.Price)
            {
                PurchaseBtn.Disabled = true;
            }
            else
            {
                PurchaseBtn.Disabled = false;
            }
            PurchaseBtn.Text = $"${rewardProto.Price}";
            PurchaseBtn.OnPressed += PurchaseBtn_OnPressed;
        }
        else
        {
            PurchaseBtn.Text = "Locked";
            PurchaseBtn.Disabled = true;
        }

    }

    private void PurchaseBtn_OnPressed(BaseButton.ButtonEventArgs obj)
    {
        _owner.RumorRewardPurchase(_rewardID, _levelID, _factionID);
    }
}
