using Content.Shared._Persistence14.Rumors.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.CrewAssignments.UI;

[GenerateTypedNameReferences]
public sealed partial class RumorRewardBoxFragment : PanelContainer
{
    [Dependency] private IPrototypeManager _protoManager = default!;
    [Dependency] private IEntityManager _entMan = default!;
    public int RumorIndex = 0;
    public RumorRewardBoxFragment(ActiveRumorReward activeRumor, bool unlocked)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        this.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = Color.Black
        };
        var spriteSystem = _entMan.System<SpriteSystem>();
        var rewardProto = _protoManager.Index<RumorRewardPrototype>(activeRumor.Reward);
        Icon.Texture = spriteSystem.Frame0(rewardProto.Icon);
        TitleLabel.Text = rewardProto.Name;
        ContentLabel.Text = rewardProto.Description;
        AvailableAtLbl.Text = $"[italic][color=gray]Import to {activeRumor.TradeStationName}";
        if(unlocked)
        {
            PurchaseBtn.Text = $"${rewardProto.Price}";
            PurchaseBtn.Disabled = false;
        }
        else
        {
            PurchaseBtn.Text = "Locked";
            PurchaseBtn.Disabled = true;
        }
    }
}
