using Content.Shared._Persistence14.Rumors.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.CrewAssignments.UI;

[GenerateTypedNameReferences]
public sealed partial class RumorBoxFragment : PanelContainer
{
    [Dependency] private IPrototypeManager _protoManager = default!;

    public int RumorIndex = 0;
    public RumorBoxFragment(ActiveRumor activeRumor)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var factionProto = _protoManager.Index<MetaFactionPrototype>(activeRumor.Faction);
        this.PanelOverride = new StyleBoxFlat
        {
            BorderColor = factionProto.Color,
            BorderThickness = new Thickness(5f),
            BackgroundColor = Color.Black
        };
        TitleLabel.Text = activeRumor.Name;
        ContentLabel.Text = activeRumor.Description;
        RewardLabel.Text = "";
        bool newline = false;
        if(activeRumor.CashReward != 0)
        {
            RewardLabel.Text += $"[color=green]${activeRumor.CashReward}[/color]";
            newline = true;
        }
        if(activeRumor.ReputationReward != 0)
        {
            if (newline) RewardLabel.Text += "\n";
            RewardLabel.Text += $"[color=orange]{activeRumor.ReputationReward} REP ({factionProto.Name})[/color]";
            newline = true;
        }
        var originalProto = _protoManager.Index<RumorPrototype>(activeRumor.OriginalPrototype);
        if(originalProto.RewardRumors != 0)
        {
            if (newline) RewardLabel.Text += "\n";
            RewardLabel.Text += $"[color=yellow]This will lead to a rewarding rumor[/color]";
        }
        
    }
}
