using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class TechnologyCardControl : Control
{
    public Action? OnPressed;

    private bool _expanded = false;

    public TechnologyCardControl(TechnologyPrototype technology, IPrototypeManager prototypeManager, SpriteSystem spriteSys, FormattedMessage description, int points, bool hasAccess)
    {
        RobustXamlLoader.Load(this);

        var discipline = prototypeManager.Index<TechDisciplinePrototype>(technology.Discipline);
        Background.ModulateSelfOverride = discipline.Color;

        DisciplineTexture.Texture = spriteSys.Frame0(discipline.Icon);
        TechnologyNameLabel.Text = Truncate(Loc.GetString(technology.Name), 28);
        TechnologyNameLabel.OnResized += () =>
            UpdateLabelName(TechnologyNameLabel, Loc.GetString(technology.Name), 7f);

        CollapsedTechnologyNameLabel.Text = Truncate(Loc.GetString(technology.Name), 28);
        CollapsedTechnologyNameLabel.OnResized += () =>
            UpdateLabelName(CollapsedTechnologyNameLabel, Loc.GetString(technology.Name), 7f);

        var message = new FormattedMessage();
        message.AddMarkupOrThrow(Loc.GetString("research-console-tier-discipline-info",
            ("tier", technology.Tier), ("color", discipline.Color), ("discipline", Loc.GetString(discipline.Name))));
        TierLabel.SetMessage(message);
        UnlocksLabel.SetMessage(description);

        TechnologyTexture.Texture = spriteSys.Frame0(technology.Icon);

        if (!hasAccess)
        {
            ResearchButton.ToolTip = Loc.GetString("research-console-no-access-popup");
            CollapsedResearchButton.ToolTip = Loc.GetString("research-console-no-access-popup");
        }

        ResearchButton.Disabled = points < technology.Cost || !hasAccess;
        CollapsedResearchButton.Disabled = points < technology.Cost || !hasAccess;
        ResearchButton.OnPressed += _ => OnPressed?.Invoke();
        CollapsedResearchButton.OnPressed += _ => OnPressed?.Invoke();

        ExpandButton.OnPressed += _ => SetExpanded(true);
        CollapseButton.OnPressed += _ => SetExpanded(false);

        SetExpanded(false);
    }

    private void SetExpanded(bool expanded)
    {
        _expanded = expanded;

        CollapsedMainButton.Visible = !_expanded;
        MainButton.Visible = _expanded;
    }

    private void UpdateLabelName(Label label, string name, float fontWidth)
    {
        var availableWidth = label.PixelSize.X;
        if (availableWidth <= 0)
            return;

        var characters = (int)(availableWidth / fontWidth);

        label.Text = Truncate(name, characters);
    }

    private static string Truncate(string text, int maxLength, string ending = "...")
    {
        if (text.Length <= maxLength)
            return text;

        return $"{text[..(maxLength - ending.Length)].TrimEnd()}{ending}";
    }
}
