using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.MessageBoard.UI;

[GenerateTypedNameReferences]
public sealed partial class CommentHeader : PanelContainer
{
    public CommentHeader(string content, string author, string date, bool deleteEnabled)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        CommentLabel.Text = content;
        AuthorLabel.Text = $"Posted by {author} on {date}";
        DeleteButton.Visible = deleteEnabled;
    }
}
