using Content.Client.Message;
using Content.Shared.CCVar;
using Content.Shared.CrewMetaRecords;
using Content.Shared.MessageBoard.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;


namespace Content.Client.MessageBoard.UI;

[GenerateTypedNameReferences]
public sealed partial class ConversationWindow : DefaultWindow
{
    [Dependency] private readonly IConfigurationManager _cfg = default!;

    public DirectMessageConversation Entry;
    private bool _isAdmin;
    private string _playerName;
    public string RecipientName;

    public ConversationWindow(DirectMessageConversation entry, bool isAdmin, string playerName, string recipientName)
    {
        RecipientName = recipientName;
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        Entry = entry;
        _isAdmin = isAdmin;
        _playerName = playerName;
        Title = recipientName;
        var yearOffset = _cfg.GetCVar(CCVars.YearOffset);
        foreach (var message in entry.Messages)
        {
            var finalTime = message.SendTime.AddYears(yearOffset);
            Label label = new();
            label.Text = $"{message.Sender} ({finalTime}): {message.Body}";
            MessagesBC.AddChild(label);

        }
    }

    public void UpdateEntry(DirectMessageConversation entry)
    {
        Entry = entry;
        MessagesBC.DisposeAllChildren();
        foreach (var message in entry.Messages)
        {
            Label label = new();
            label.Text = $"{message.Sender} ({message.SendTime}): {message.Body}";
            MessagesBC.AddChild(label);

        }
    }
}
