using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;

namespace Content.Client.MessageBoard.UI;
[GenerateTypedNameReferences]
public sealed partial class CreateEntry : DefaultWindow
{
    public enum EntryType : byte
    {
        Public,
        Direct
    }

    public EntryType CurrentEntryType = EntryType.Public;

}

