using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.MessageBoard.UI;

[GenerateTypedNameReferences]
public sealed partial class EntryHeader : PanelContainer
{
    public EntryHeader(string title, string author, string date, int commentCount, bool deleteEnabled)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        TitleLabel.Text = title;
        AuthorLabel.Text = $"Posted by {author}";
        DateLabel.Text = date;
        CommentsLabel.Text = $"{commentCount} Comments";
        DeleteButton.Visible = deleteEnabled;
    }
}
