using Content.Client.Message;
using Content.Shared.CCVar;
using Content.Shared.MessageBoard.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;


namespace Content.Client.MessageBoard.UI;

[GenerateTypedNameReferences]
public sealed partial class EntryWindow : DefaultWindow
{
    [Dependency] private readonly IConfigurationManager _cfg = default!;

    public MessageBoardEntry Entry;
    private bool _isAdmin;
    private string _playerName;
    private MessageBoardBoundUserInterface _owner;

    public EntryWindow(MessageBoardEntry entry, bool isAdmin, string playerName, MessageBoardBoundUserInterface owner)
    {
        _owner = owner;
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        Entry = entry;
        this.Title = entry.Title;
        _isAdmin = isAdmin;
        _playerName = playerName;
        MainTitleLabel.Text = entry.Title;
        var adjustedMainTime = entry.CreationTime.AddYears(_cfg.GetCVar(CCVars.YearOffset));
        AuthorLabel.Text = $"Posted by {entry.Author} on {adjustedMainTime.ToString()}";
        MainContentLabel.SetMarkup(entry.Body);
        entry.Comments.Reverse();
        foreach (var comment in entry.Comments)
        {
            var adjustedTime = comment.CreationTime.AddYears(_cfg.GetCVar(CCVars.YearOffset));
            bool delete = false;
            if (_isAdmin || _playerName == comment.Author) delete = true;
            var item = new CommentHeader(comment.Body, comment.Author, $"{adjustedTime.ToString()}", delete);
            CommentBC.AddChild(item);
            item.DeleteButton.OnPressed += (args) =>
            {
                var ID = comment.UID;
                _owner.SendMessage(new MessageBoardDeleteCommentPublicMessage(ID, Entry.UID));
            };
        }

    }

    public void UpdateEntry(MessageBoardEntry entry)
    {
        Entry = entry;
        this.Title = entry.Title;
        MainTitleLabel.Text = entry.Title;
        var adjustedMainTime = entry.CreationTime.AddYears(_cfg.GetCVar(CCVars.YearOffset));
        AuthorLabel.Text = $"Posted by {entry.Author} on {adjustedMainTime.ToString()}";
        MainContentLabel.SetMarkup(entry.Body);
        CommentBC.RemoveAllChildren();
        entry.Comments.Reverse();
        foreach (var comment in entry.Comments)
        {
            var adjustedTime = comment.CreationTime.AddYears(_cfg.GetCVar(CCVars.YearOffset));
            bool delete = false;
            if (_isAdmin || _playerName == comment.Author) delete = true;
            CommentBC.AddChild(new CommentHeader(comment.Body, comment.Author, $"{adjustedTime.ToString()}", delete));
        }
    }
}
