# Base prototypes

- type: latheRecipe
  abstract: true
  id: BaseShieldRecipe
  categories:
  - Tools
  completetime: 4

- type: latheRecipe
  abstract: true
  id: BaseTargetRecipe
  categories:
  - Tools
  completetime: 5
  applyMaterialDiscount: false # ingredients dropped when destroyed
  materials:
    Steel: 500

- type: latheRecipe
  abstract: true
  id: BaseWeaponRecipe
  categories:
  - Weapons

- type: latheRecipe
  abstract: true
  parent: BaseWeaponRecipe
  id: BaseWeaponRecipeMelee
  completetime: 2

- type: latheRecipe
  abstract: true
  parent: BaseWeaponRecipe
  id: BaseWeaponRecipePractice
  completetime: 4

- type: latheRecipe
  abstract: true
  parent: BaseWeaponRecipe
  id: BaseWeaponRecipeLong
  completetime: 5

- type: latheRecipe
  abstract: true
  parent: BaseWeaponRecipe
  id: BaseWeaponRecipeSidearm
  completetime: 6

- type: latheRecipe
  abstract: true
  id: BaseShoesClothingRecipeSecurity
  categories:
  - Shoes
  completetime: 2
  materials:
    Cloth: 200
    Durathread: 200
    Plasteel: 200

## Recipes

# Clothing
- type: latheRecipe
  id: ClothingBackpackElectropack
  result: ClothingBackpackElectropack
  categories:
  - Clothing
  completetime: 4
  materials:
    Steel: 500
    Plastic: 250
    Cloth: 500

# Moffstation - Begin - Replaced by modular HUDs
#- type: latheRecipe
#  id: ClothingEyesHudSecurity
#  result: ClothingEyesHudSecurity
#  categories:
#  - Clothing
#  completetime: 2
#  materials:
#    Steel: 300
#    Glass: 200
# Moffstation - End

- type: latheRecipe
  id: PortableRecharger
  result: PortableRecharger
  categories:
  - Clothing
  completetime: 15
  materials:
    Steel: 2000
    Uranium: 2000
    Plastic: 1000
    Plasma: 500
    Glass: 500

- type: latheRecipe
  id: ClothingBackpackHarmpack
  result: ClothingBackpackHarmpack
  categories:
  - Clothing
  completetime: 15
  materials:
    Steel: 2000
    Plastic: 1000
    Plasma: 500
    Gold: 500

# Shields
- type: latheRecipe
  parent: BaseShieldRecipe
  id: RiotShield
  result: RiotShield
  materials:
    Steel: 400
    Glass: 400

- type: latheRecipe
  parent: BaseShieldRecipe
  id: TelescopicShield
  result: TelescopicShield
  materials:
    Steel: 300
    Glass: 800
  unlockUses: 4

- type: latheRecipe
  parent: BaseShieldRecipe
  id: RiotLaserShield
  result: RiotLaserShield
  materials:
    Steel: 300
    Glass: 400
  unlockUses: 4



# Targets
- type: latheRecipe
  parent: BaseTargetRecipe
  id: TargetHuman
  result: TargetHuman

- type: latheRecipe
  parent: BaseTargetRecipe
  id: TargetClown
  result: TargetClown

- type: latheRecipe
  parent: BaseTargetRecipe
  id: TargetSyndicate
  result: TargetSyndicate

# Tools
- type: latheRecipe
  parent: BaseToolRecipe
  id: Handcuffs
  result: Handcuffs
  materials:
    Steel: 300

- type: latheRecipe
  parent: BaseToolRecipe
  id: Zipties
  result: Zipties
  materials:
    Plastic: 200

- type: latheRecipe
  parent: BaseToolRecipe
  id: ForensicPad
  result: ForensicPad
  completetime: 4
  materials:
    Plastic: 100

- type: latheRecipe
  parent: BaseToolRecipe
  id: HoloprojectorSecurity
  result: HoloprojectorSecurityEmpty
  materials:
    Steel: 300
    Glass: 50
    Plastic: 50
  unlockUses: 4

- type: latheRecipe
  parent: BaseToolRecipe
  id: Flash
  result: Flash
  materials:
    Glass: 100
    Plastic: 200
    Steel: 100

## Weapons

# Melee
- type: latheRecipe
  parent: BaseWeaponRecipeMelee
  id: Stunbaton
  result: Stunbaton
  materials:
    Steel: 300
    Plastic: 300

- type: latheRecipe
  parent: BaseWeaponRecipeMelee
  id: Truncheon
  result: Truncheon
  materials:
    Steel: 300
    Plastic: 300
  unlockUses: 4

- type: latheRecipe
  parent: BaseWeaponRecipeMelee
  id: CombatKnife
  result: CombatKnife
  materials:
    Steel: 250
    Plastic: 100

# Practice weapons
- type: latheRecipe
  parent: BaseWeaponRecipePractice
  id: WeaponDisablerPractice
  result: WeaponDisablerPractice
  materials:
    Steel: 500
    Glass: 100
    Plastic: 200

- type: latheRecipe
  parent: BaseWeaponRecipePractice
  id: WeaponLaserCarbinePractice
  result: WeaponLaserCarbinePractice
  materials:
    Steel: 1800
    Glass: 400
    Plastic: 250

# Long Guns
- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponLaserCarbine
  result: WeaponLaserCarbine
  materials:
    Steel: 2000
    Glass: 800
    Plastic: 500
  unlockUses: 2

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponAdvancedLaser
  result: WeaponAdvancedLaser
  materials:
    Steel: 1500
    Glass: 1000
    Gold: 500
    Uranium: 300
  unlockUses: 1

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponLaserCannon
  result: WeaponLaserCannon
  materials:
    Steel: 1250
    Plastic: 750
    Gold: 350
  unlockUses: 1

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponXrayCannon
  result: WeaponXrayCannon
  materials:
    Steel: 1500
    Glass: 500
    Plastic: 250
    Gold: 250
  unlockUses: 1

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponTemperatureGun
  result: WeaponTemperatureGun
  materials:
    Steel: 2000
    Glass: 500
    Plastic: 500
    Gold: 500
  unlockUses: 1

# Sidearms
- type: latheRecipe
  parent: BaseWeaponRecipeSidearm
  id: WeaponDisabler
  result: WeaponDisabler
  materials:
    Steel: 300
    Glass: 200
    Plastic: 200
  unlockUses: 4

- type: latheRecipe
  parent: BaseWeaponRecipeSidearm
  id: WeaponDisablerSMG
  result: WeaponDisablerSMG
  materials:
    Steel: 1000
    Glass: 500
    Plastic: 500
  unlockUses: 2

- type: latheRecipe
  parent: BaseWeaponRecipeSidearm
  id: WeaponLaserSvalinn
  result: WeaponLaserSvalinn
  materials:
    Steel: 2000
    Gold: 500
  unlockUses: 1

- type: latheRecipe
  parent: BaseWeaponRecipeSidearm
  id: WeaponFlareGunSecurity
  result: WeaponFlareGunSecurity
  materials:
    Plastic: 100
    Steel: 400

- type: latheRecipe
  parent: BaseToolRecipe
  id: ClothingBeltTanMilitaryWebbing
  result: ClothingBeltTanMilitaryWebbing
  materials:
    Plastic: 400

- type: latheRecipe
  parent: BaseToolRecipe
  id: ClothingHeadHelmetMilitaryWoodland
  result: ClothingHeadHelmetMilitaryWoodland
  materials:
    Steel: 500
    Plastic: 100

- type: latheRecipe
  parent: BaseToolRecipe
  id: ClothingHeadHelmetMilitaryArctic
  result: ClothingHeadHelmetMilitaryArctic
  materials:
    Steel: 500
    Plastic: 100

- type: latheRecipe
  parent: BaseToolRecipe
  id: ClothingHeadHelmetMilitaryDesert
  result: ClothingHeadHelmetMilitaryDesert
  materials:
    Steel: 500
    Plastic: 100

- type: latheRecipe
  parent: BaseToolRecipe
  id: ClothingHeadHelmetRiot
  result: ClothingHeadHelmetRiot
  materials:
    Steel: 500
    Plastic: 200

- type: latheRecipe
  parent: BaseToolRecipe
  id: ClothingHeadHelmetBasic
  result: ClothingHeadHelmetBasic
  materials:
    Steel: 500
    Plastic: 100

- type: latheRecipe
  parent: BaseToolRecipe
  id: ClothingMaskGasSecurity
  result: ClothingMaskGasSecurity
  materials:
    Steel: 500
    Plastic: 100

- type: latheRecipe
  parent: BaseGlovesClothingRecipeInsulated
  id: ClothingHandsMercGlovesCombat
  result: ClothingHandsMercGlovesCombat
  unlockUses: 4

- type: latheRecipe
  parent: BaseGlovesClothingRecipeInsulated
  id: ClothingHandsTacticalMaidGloves
  result: ClothingHandsTacticalMaidGloves
  unlockUses: 4

- type: latheRecipe
  parent: BaseGlovesClothingRecipeInsulated
  id: ClothingHandsGlovesCombat
  result: ClothingHandsGlovesCombat
  unlockUses: 4

- type: latheRecipe
  parent: BaseBeltsClothingRecipe
  id: ClothingBeltSecurity
  result: ClothingBeltSecurity
  materials:
    Cloth: 400
    Durathread: 100

- type: latheRecipe
  parent: BaseBeltsClothingRecipe
  id: ClothingBeltHolster
  result: ClothingBeltHolster

- type: latheRecipe
  parent: BaseBeltsClothingRecipe
  id: ClothingBeltBandolier
  result: ClothingBeltBandolier

- type: latheRecipe
  parent: BaseBeltsClothingRecipe
  id: ClothingBeltSecurityWebbing
  result: ClothingBeltSecurityWebbing
  materials:
    Cloth: 400
    Durathread: 300

- type: latheRecipe
  parent: BaseBeltsClothingRecipe
  id: ClothingBeltMercWebbing
  result: ClothingBeltMercWebbing
  materials:
    Cloth: 400
    Durathread: 300

- type: latheRecipe
  parent: BaseBeltsClothingRecipe
  id: ClothingBeltMilitaryWebbing
  result: ClothingBeltMilitaryWebbing
  materials:
    Cloth: 400
    Durathread: 300

- type: latheRecipe
  parent: BaseGlassesClothingRecipe
  id: ClothingEyesGlassesSecurity
  result: ClothingEyesGlassesSecurity
  materials:
    Steel: 100
    Plastic: 50
    Plasteel: 100
    ReinforcedGlass: 200

- type: latheRecipe
  parent: BaseGlassesClothingRecipe
  id: ClothingEyesGlassesMercenary
  result: ClothingEyesGlassesMercenary
  materials:
    Steel: 100
    ReinforcedGlass: 200

- type: latheRecipe
  parent: BaseShoesClothingRecipeSecurity
  id: ClothingShoesBootsJack
  result: ClothingShoesBootsJack

- type: latheRecipe
  parent: BaseShoesClothingRecipeSecurity
  id: ClothingShoesBootsCombat
  result: ClothingShoesBootsCombat

- type: latheRecipe
  parent: BaseShoesClothingRecipeSecurity
  id: ClothingShoesHighheelBoots
  result: ClothingShoesHighheelBoots

- type: latheRecipe
  parent: BaseShoesClothingRecipeSecurity
  id: ClothingShoesBootsMerc
  result: ClothingShoesBootsMerc

- type: latheRecipe
  parent: BaseShoesClothingRecipeSecurity
  id: ClothingShoesBootsWinterSec
  result: ClothingShoesBootsWinterSec

- type: latheRecipe
  parent: BaseShoesClothingRecipeSecurity
  id: ClothingShoesBootsCowboyBrown
  result: ClothingShoesBootsCowboyBrown

- type: latheRecipe
  parent: BaseShoesClothingRecipeSecurity
  id: ClothingShoesBootsCowboyBlack
  result: ClothingShoesBootsCowboyBlack

- type: latheRecipe
  parent: BaseShoesClothingRecipeSecurity
  id: ClothingShoesBootsCowboyWhite
  result: ClothingShoesBootsCowboyWhite

- type: latheRecipe
  parent: BaseShoesClothingRecipeSecurity
  id: ClothingShoesBootsCowboyFancy
  result: ClothingShoesBootsCowboyFancy
