using Content.Shared.CartridgeLoader.Cartridges;
using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class LogProbeUiFragment : BoxContainer
{
    [Dependency] private readonly IConfigurationManager _cfgManager = default!;
    /// <summary>
    /// Action invoked when the print button gets pressed.
    /// </summary>
    public Action? OnPrintPressed;

    public LogProbeUiFragment()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        PrintButton.OnPressed += _ => OnPrintPressed?.Invoke();
    }

    public void UpdateState(string name, List<PulledAccessLog> logs)
    {
        EntityName.Text = name;
        PrintButton.Disabled = string.IsNullOrEmpty(name);

        ProbedDeviceContainer.RemoveAllChildren();

        var count = 1;
        foreach (var log in logs)
        {
            AddAccessLog(log, count);
            count++;
        }
    }

    private void AddAccessLog(PulledAccessLog log, int numberLabelText)
    {
        var yearOffset = _cfgManager.GetCVar(CCVars.YearOffset);
        var finalTime = log.Time.AddYears(yearOffset);
        var timeLabelText = (finalTime).ToString();
        var accessorLabelText = log.Accessor;

        var entry = new LogProbeUiEntry(numberLabelText, timeLabelText, accessorLabelText);

        ProbedDeviceContainer.AddChild(entry);
    }
}
