using Content.Client.Humanoid;
using Content.Client.Lobby.UI.Roles;
using Content.Client.Message;
using Content.Client.Players.PlayTimeTracking;
using Content.Client.Sprite;
using Content.Shared._Persistence14.Background.Prototypes;
using Content.Shared.CCVar;
using Content.Shared.GameTicking;
using Content.Shared.Guidebook;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Markings;
using Content.Shared.Preferences;
using Content.Shared.Traits;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Utility;
using Robust.Shared.Configuration;
using Robust.Shared.Console.Commands;
using Robust.Shared.ContentPack;
using Robust.Shared.Enums;
using Robust.Shared.Prototypes;
using System.Linq;
using Direction = Robust.Shared.Maths.Direction;

namespace Content.Client.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class HumanoidProfileEditor : BoxContainer
    {
        private readonly IClientPreferencesManager _preferencesManager;
        private readonly IConfigurationManager _cfgManager;
        private readonly IEntityManager _entManager;
        private readonly IFileDialogManager _dialogManager;
        private readonly IPlayerManager _playerManager;
        private readonly IPrototypeManager _prototypeManager;
        private readonly IResourceManager _resManager;
        private readonly MarkingManager _markingManager;
        private readonly JobRequirementsManager _requirements;
        private readonly LobbyUIController _controller;

        private readonly SpriteSystem _sprite;

        // CCvar.
        private int _maxNameLength;

        /// <summary>
        /// If we're attempting to save.
        /// </summary>
        public event Action? Save;

        /// <summary>
        /// If we're attempting to join.
        /// </summary>
        public event Action? Join;

        /// <summary>
        /// Entity used for the profile editor preview
        /// </summary>
        public EntityUid PreviewDummy;


        /// <summary>
        /// The character slot for the current profile.
        /// </summary>
        public int? CharacterSlot;

        /// <summary>
        /// The work in progress profile being edited.
        /// </summary>
        public HumanoidCharacterProfile? Profile;

        private Direction _previewRotation = Direction.North;

        private bool _isDirty;

        public bool IsDirty
        {
            get => _isDirty;
            set
            {
                if (_isDirty == value)
                    return;

                _isDirty = value;
                UpdateSaveButton();
            }
        }

        private ISawmill _sawmill;

        public string ThresholdLore = "Travel into the Threshold is strictly one way and so you left everything behind the moment you passed through the true-space barrier.";

        public Dictionary<string, string> Sigils = new Dictionary<string, string>
        {
            { "The Whale", "[bold]Dreaming is impossible in the perfect void of cryosleep.[/bold]\n\nBut as you enter the Threshold you dream of a whale. When it opens its mouth it reveals a giant blue crystal protruding up from its throat.\n\nYour shipmates haul it aboard and start butchering it. The fumes make your eyes and mouth burn viciously." },
            { "The Lock", "[bold]Dreaming is impossible in the perfect void of cryosleep.[/bold]\n\nBut as you enter the Threshold you dream of a lock. It holds the doors of your cage shut until the day of your execution.\n\nAfter you die you still aren't free, as they put your soul into a vault. All you can see is the lock." },
            { "The Show", "[bold]Dreaming is impossible in the perfect void of cryosleep.[/bold]\n\nBut as you enter the Threshold you dream of a show. It's the story of your life as a show. In the show you are rejected from joining the crew into the Threshold.\n\nThe show continues on but you cant keep watching it. The signal cant reach." },
            { "The Thought", "[bold]Dreaming is impossible in the perfect void of cryosleep.[/bold]\n\nBut as you enter the Threshold you dream of a thought. It exists in two places at once and what else could?\n\nIt clamors upwards and happily takes its place along with the others. They are building a gate." },
            { "The Void", "[bold]Dreaming is impossible in the perfect void of cryosleep.[/bold]\n\nBut as you enter the Threshold the void grows even darker than pitch. You hit the surface of nothingness and go beneath the waters\n\nIt's so cold and when you look up you see yourself looking down at a reflection." }
        };

        private MarkingsViewModel _markingsModel = new();

        public HumanoidProfileEditor(
            IClientPreferencesManager preferencesManager,
            IConfigurationManager configurationManager,
            IEntityManager entManager,
            IFileDialogManager dialogManager,
            ILogManager logManager,
            IPlayerManager playerManager,
            IPrototypeManager prototypeManager,
            IResourceManager resManager,
            JobRequirementsManager requirements,
            MarkingManager markings)
        {
            RobustXamlLoader.Load(this);
            _sawmill = logManager.GetSawmill("profile.editor");
            _cfgManager = configurationManager;
            _entManager = entManager;
            _dialogManager = dialogManager;
            _playerManager = playerManager;
            _prototypeManager = prototypeManager;
            _markingManager = markings;
            _preferencesManager = preferencesManager;
            _resManager = resManager;
            _requirements = requirements;
            _controller = UserInterfaceManager.GetUIController<LobbyUIController>();
            _sprite = _entManager.System<SpriteSystem>();

            _maxNameLength = _cfgManager.GetCVar(CCVars.MaxNameLength);
            _allowFlavorText = _cfgManager.GetCVar(CCVars.FlavorText);
            AlignmentButton.AddItem("*UNSELECTED*");
            foreach (var alignment in _prototypeManager.EnumeratePrototypes<AlignmentPrototype>())
            {
                AlignmentButton.AddItem(alignment.Name);
            }


            AlignmentButton.OnItemSelected += args =>
            {
                SelectAlignment(args);
            };
            BGButton.AddItem("*UNSELECTED*");
            foreach (var background in _prototypeManager.EnumeratePrototypes<UniverseOriginPrototype>())
            {
                BGButton.AddItem(background.Name);
            }

            BGButton.OnItemSelected += args =>
            {
                SelectUniverseOrigin(args);
            };

            MotiveButton.AddItem("*UNSELECTED*");
            foreach (var motive in _prototypeManager.EnumeratePrototypes<MotivePrototype>())
            {
                MotiveButton.AddItem(motive.Name);
            }
            MotiveButton.OnItemSelected += SelectMotive();

            ThresholdLoreLabel.Text = ThresholdLore;
            foreach (var kv in Sigils)
            {
                SigilButton.AddItem(kv.Key);
            }
            SigilButton.OnItemSelected += args =>
            {
                var e = Sigils.ElementAt(args.Id);
                SigilTitle.Text = e.Key;
                SigilLabel.Text = e.Value;
                SigilButton.SelectId(args.Id);
            };
            SigilButton.Select(0);
            var e = Sigils.ElementAt(0);
            SigilTitle.Text = e.Key;
            SigilLabel.Text = e.Value;

            Markings.SetModel(_markingsModel);

            ImportButton.OnPressed += args =>
            {
                ImportProfile();
            };

            ExportButton.OnPressed += args =>
            {
                ExportProfile();
            };

            ExportImageButton.OnPressed += args =>
            {
                ExportImage();
            };

            OpenImagesButton.OnPressed += args =>
            {
                _resManager.UserData.OpenOsWindow(ContentSpriteSystem.Exports);
            };

            ResetButton.OnPressed += args =>
            {
                SetProfile((HumanoidCharacterProfile?)_preferencesManager.Preferences?.SelectedCharacter, _preferencesManager.Preferences?.SelectedCharacterIndex);
            };

            SaveButton.OnPressed += args =>
            {
                Save?.Invoke();
            };
            JoinGameButton.OnPressed += args =>
            {
                Join?.Invoke();
            };

            #region Left

            #region Name

            NameEdit.OnTextChanged += args => { SetName(args.Text); };
            NameEdit.IsValid = args => args.Length <= _maxNameLength;
            RandomizeUnlockedButton.OnPressed += args => { RandomizeProfile(); };
            WarningLabel.SetMarkup($"[color=red]{Loc.GetString("humanoid-profile-editor-naming-rules-warning")}[/color]");

            #endregion Name

            #region Appearance

            TabContainer.SetTabTitle(0, Loc.GetString("humanoid-profile-editor-appearance-tab"));

            #region Sex

            SexButton.OnItemSelected += args =>
            {
                SexButton.SelectId(args.Id);
                SetSex((Sex)args.Id);
            };

            #endregion Sex

            #region Voice

            VoiceButton.OnItemSelected += args =>
            {
                VoiceButton.SelectId(args.Id);
                SetVoice(_voices[args.Id]);
            };

            #endregion

            #region Age

            AgeEdit.OnTextChanged += args =>
            {
                if (!int.TryParse(args.Text, out var newAge))
                    return;

                SetAge(newAge);
            };

            #endregion Age

            #region Gender

            PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-male-text"), (int)Gender.Male);
            PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-female-text"), (int)Gender.Female);
            PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-epicene-text"), (int)Gender.Epicene);
            PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-neuter-text"), (int)Gender.Neuter);

            PronounsButton.OnItemSelected += args =>
            {
                PronounsButton.SelectId(args.Id);
                SetGender((Gender)args.Id);
            };

            #endregion Gender

            RefreshSpecies();

            SpeciesButton.OnItemSelected += args =>
            {
                SpeciesButton.SelectId(args.Id);
                SetSpecies(_species[args.Id].ID);
                OnSkinColorOnValueChanged();
            };

            #region Skin

            Skin.OnValueChanged += _ =>
            {
                OnSkinColorOnValueChanged();
            };

            RgbSkinColorContainer.AddChild(_rgbSkinColorSelector = new ColorSelectorSliders());
            _rgbSkinColorSelector.SelectorType = ColorSelectorSliders.ColorSelectorType.Hsv; // defaults color selector to HSV
            _rgbSkinColorSelector.OnColorChanged += _ =>
            {
                OnSkinColorOnValueChanged();
            };

            #endregion

            #region SpawnPriority

            foreach (var value in Enum.GetValues<SpawnPriorityPreference>())
            {
                SpawnPriorityButton.AddItem(Loc.GetString($"humanoid-profile-editor-preference-spawn-priority-{value.ToString().ToLower()}"), (int)value);
            }

            SpawnPriorityButton.OnItemSelected += args =>
            {
                SpawnPriorityButton.SelectId(args.Id);
                SetSpawnPriority((SpawnPriorityPreference)args.Id);
            };

            #endregion SpawnPriority

            #region Eyes

            EyeColorPicker.OnEyeColorPicked += newColor =>
            {
                if (Profile is null)
                    return;
                Profile = Profile.WithCharacterAppearance(
                    Profile.Appearance.WithEyeColor(newColor));
                _markingsModel.SetOrganEyeColor(Profile.Appearance.EyeColor);
                ReloadProfilePreview();
            };

            #endregion Eyes

            #endregion Appearance

            #region Jobs

            TabContainer.SetTabTitle(1, Loc.GetString("humanoid-profile-editor-markings-tab"));

            _jobCategories = new Dictionary<string, BoxContainer>();

            RefreshAntags();
            RefreshJobs();

            #endregion Jobs


            RefreshTraits();

            #region Markings


            _markingsModel.MarkingsChanged += (_, _) => OnMarkingChange();
            _markingsModel.MarkingsReset += OnMarkingChange;

            #endregion Markings

            RefreshFlavorText();

            #region Dummy

            SpriteRotateLeft.OnPressed += _ =>
            {
                _previewRotation = _previewRotation.TurnCw();
                SetPreviewRotation(_previewRotation);
            };
            SpriteRotateRight.OnPressed += _ =>
            {
                _previewRotation = _previewRotation.TurnCcw();
                SetPreviewRotation(_previewRotation);
            };

            #endregion Dummy

            #endregion Left

            ShowClothes.OnToggled += args =>
            {
                ReloadPreview();
            };

            SpeciesInfoButton.OnPressed += OnSpeciesInfoButtonPressed;

            UpdateSpeciesGuidebookIcon();
            if (Profile == null)
            {
                Profile = new HumanoidCharacterProfile();
            }
            SetDirty();
            CheckReady();
        }

        private Action<OptionButton.ItemSelectedEventArgs> SelectMotive()
        {
            return args =>
            {
                MotiveButton.SelectId(args.Id);
                if (args.Id == 0)
                {
                    MotiveTitleLabel.Text = string.Empty;
                    MotiveDescLabel.Text = string.Empty;
                    Profile?.Motive = null;
                    CheckReady();
                    RefreshBackgroundTraits();
                    return;
                }
                var motiveslist = _prototypeManager.EnumeratePrototypes<MotivePrototype>().ToList();
                var ind = args.Id - 1;
                if (ind < 0 || ind >= motiveslist.Count)
                    return;
                var e = motiveslist.ElementAt(ind);
                MotiveTitleLabel.Text = e.Name;
                MotiveDescLabel.Text = e.Description;
                MotiveEffectsLabel.Text = "";
                foreach (var effect in e.Effects)
                {
                    var effectProto = _prototypeManager.Index<BackgroundEffectPrototype>(effect);
                    MotiveEffectsLabel.Text += $"\n{effectProto.Description}";
                }
                Profile?.Motive = e.ID;
                CheckReady();
                RefreshBackgroundTraits();
            };
        }

        private void SelectUniverseOrigin(OptionButton.ItemSelectedEventArgs args)
        {
            BGButton.SelectId(args.Id);
            if (args.Id == 0)
            {
                BGTitleLabel.Text = string.Empty;
                BGDescLabel.Text = string.Empty;
                Profile?.UniverseOrigin = null;
                CheckReady();
                RefreshBackgroundTraits();
                return;
            }
            var backgroundslist = _prototypeManager.EnumeratePrototypes<UniverseOriginPrototype>().ToList();
            var ind = args.Id - 1;
            if (ind < 0 || ind >= backgroundslist.Count)
                return;
            var e = backgroundslist.ElementAt(ind);
            BGTitleLabel.Text = e.Name;
            BGDescLabel.Text = e.Description;
            BGEffectsLabel.Text = "";
            foreach (var effect in e.Effects)
            {
                var effectProto = _prototypeManager.Index<BackgroundEffectPrototype>(effect);
                BGEffectsLabel.Text += $"\n{effectProto.Description}";
            }
            Profile?.UniverseOrigin = e.ID;
            CheckReady();
            RefreshBackgroundTraits();
            return;
        }

        private void SelectAlignment(OptionButton.ItemSelectedEventArgs args)
        {
            AlignmentButton.SelectId(args.Id);
            if (args.Id == 0)
            {
                AlignTitleLabel.Text = string.Empty;
                AlignDescLabel.Text = string.Empty;
                AlignEffectsLabel.Text = string.Empty;
                Profile?.Alignment = null;
                CheckReady();
                RefreshBackgroundTraits();
                return;
            }
            var alignmentslist = _prototypeManager.EnumeratePrototypes<AlignmentPrototype>().ToList();
            var ind = args.Id - 1;
            if (ind < 0 || ind >= alignmentslist.Count)
                return;
            var e = alignmentslist.ElementAt(ind);
            AlignTitleLabel.Text = e.Name;
            AlignDescLabel.Text = e.Description;
            AlignEffectsLabel.Text = "";
            foreach (var effect in e.Effects)
            {
                var effectProto = _prototypeManager.Index<BackgroundEffectPrototype>(effect);
                AlignEffectsLabel.Text += $"\n{effectProto.Description}";
            }
            Profile?.Alignment = e.ID;
            CheckReady();
            RefreshBackgroundTraits();
            return;
        }

        private void RefreshBackgroundTraits()
        {
            BackgroundTraits.RemoveAllChildren();
            if (Profile == null) return;
            if (Profile.Alignment != null)
            {
                var alignment = _prototypeManager.Index<AlignmentPrototype>(Profile.Alignment);
                foreach (var effect in alignment.Effects)
                {
                    var effectProto = _prototypeManager.Index<BackgroundEffectPrototype>(effect);
                    if(effectProto.Traits.Count > 0)
                    {
                        foreach(var trait in effectProto.Traits)
                        {
                            AddBackgroundTrait(trait);
                        }
                    }
                }
                if(Profile.UniverseOrigin != null)
                {
                    var background = _prototypeManager.Index<UniverseOriginPrototype>(Profile.UniverseOrigin);
                    foreach (var effect in background.Effects)
                    {
                        var effectProto = _prototypeManager.Index<BackgroundEffectPrototype>(effect);
                        if (effectProto.Traits.Count > 0)
                        {
                            foreach (var trait in effectProto.Traits)
                            {
                                AddBackgroundTrait(trait);
                            }
                        }
                    }
                }
                if(Profile.Motive != null)
                {
                    var motive = _prototypeManager.Index<MotivePrototype>(Profile.Motive);
                    foreach (var effect in motive.Effects)
                    {
                        var effectProto = _prototypeManager.Index<BackgroundEffectPrototype>(effect);
                        if (effectProto.Traits.Count > 0)
                        {
                            foreach (var trait in effectProto.Traits)
                            {
                                AddBackgroundTrait(trait);
                            }
                        }
                    }
                }
            }
        }
        private void AddBackgroundTrait(ProtoId<TraitPrototype> traitId)
        {
            var traitProto = _prototypeManager.Index<TraitPrototype>(traitId);
            TraitPreferenceSelector traitBar = new(traitProto);
            traitBar.Checkbox.Disabled = true;
            traitBar.Checkbox.Pressed = true;
            BackgroundTraits.AddChild(traitBar);
        }
        private void CheckReady()
        {
            bool alignmentSelected = false;
            if(Profile?.Alignment != null)
            {
                alignmentSelected = true;
            }
            bool originSelected = false;
            if (Profile?.UniverseOrigin != null)
            {
                originSelected = true;
            }
            bool motiveSelected = false;
            if (Profile?.Motive != null)
            {
                motiveSelected = true;
            }
            if (alignmentSelected && originSelected && motiveSelected)
            {
                SaveButton.Disabled = false;
                RequirementsLbl.Text = "";
            }
            else
            {
                SaveButton.Disabled = true;
                RequirementsLbl.Text = "[color=red]Complete the Background Page.";
            }
            ReloadPreview();
        }
        private void SetDirty()
        {
            if (Profile == null)
            {
                Profile = new HumanoidCharacterProfile();
            }

            // Creating new character
            if (_preferencesManager.Preferences?.SelectedCharacter == null)
            {
                IsDirty = true;

                TabContainer.Visible = true;

                SaveButton.Visible = true;
                RequirementsLbl.Visible = true;
                RandomizerPanel.Visible = true;
                JoinGameButton.Visible = false;

                ImportButton.Visible = true;
                ExportButton.Visible = false;
                OpenImagesButton.Visible = false;
                ExportImageButton.Visible = false;

                ResetButton.Visible = false;
                NameEdit.Editable = true;
            }
            // Opening existing chracter
            else
            {
                IsDirty = false;

                TabContainer.Visible = false;

                SaveButton.Visible = false;
                RequirementsLbl.Visible = false;
                RandomizerPanel.Visible = false;
                JoinGameButton.Visible = true;

                ImportButton.Visible = false;
                ExportButton.Visible = true;
                OpenImagesButton.Visible = true;
                ExportImageButton.Visible = true;

                ResetButton.Visible = false;
                NameEdit.Editable = false;
            }
        }

        /// <summary>
        /// Reloads the entire dummy entity for preview.
        /// </summary>
        /// <remarks>
        /// This is expensive so not recommended to run if you have a slider.
        /// </remarks>
        private void ReloadPreview()
        {
            if (Profile == null)
                return;

            SpriteView.LoadPreview(Profile, JobOverride, ShowClothes.Pressed);

            // Check and set the dirty flag to enable the save/reset buttons as appropriate.
            SetDirty();
        }

        /// <summary>
        /// Resets the profile to the defaults.
        /// </summary>
        public void ResetToDefault()
        {
            SetProfile(
                (HumanoidCharacterProfile?)_preferencesManager.Preferences?.SelectedCharacter,
                _preferencesManager.Preferences?.SelectedCharacterIndex);
        }


        public void UpdateBackgrounds()
        {
            var motiveStatus = Profile?.Motive;
            if(motiveStatus != null)
            {
                var ind = 0;
                foreach (var motive in _prototypeManager.EnumeratePrototypes<MotivePrototype>())
                {
                    ind++;
                    if(motive.ID == motiveStatus)
                    {
                        MotiveButton.SelectId(ind);
                        MotiveTitleLabel.Text = motive.Name;
                        MotiveDescLabel.Text = motive.Description;
                        MotiveEffectsLabel.Text = "";
                        foreach (var effect in motive.Effects)
                        {
                            var effectProto = _prototypeManager.Index<BackgroundEffectPrototype>(effect);
                            MotiveEffectsLabel.Text += $"\n{effectProto.Description}";
                        }
                    }
                }
            }
            else
            {
                MotiveButton.SelectId(0);
                MotiveTitleLabel.Text = string.Empty;
                MotiveDescLabel.Text = string.Empty;
                MotiveEffectsLabel.Text = string.Empty;
            }
            var originStatus = Profile?.UniverseOrigin;
            if (originStatus != null)
            {
                var ind = 0;
                foreach (var background in _prototypeManager.EnumeratePrototypes<UniverseOriginPrototype>())
                {
                    ind++;
                    if (background.ID == originStatus)
                    {
                        BGButton.SelectId(ind);
                        BGTitleLabel.Text = background.Name;
                        BGDescLabel.Text = background.Description;
                        BGEffectsLabel.Text = "";
                        foreach (var effect in background.Effects)
                        {
                            var effectProto = _prototypeManager.Index<BackgroundEffectPrototype>(effect);
                            BGEffectsLabel.Text += $"\n{effectProto.Description}";
                        }
                    }
                }
            }
            else
            {
                BGButton.SelectId(0);
                BGTitleLabel.Text = string.Empty;
                BGDescLabel.Text = string.Empty;
                BGEffectsLabel.Text = string.Empty;
            }
            var alignmentStatus = Profile?.Alignment;
            if (alignmentStatus != null)
            {
                var ind = 0;
                foreach (var alignment in _prototypeManager.EnumeratePrototypes<AlignmentPrototype>())
                {
                    ind++;
                    if (alignment.ID == alignmentStatus)
                    {
                        AlignmentButton.SelectId(ind);
                        AlignTitleLabel.Text = alignment.Name;
                        AlignDescLabel.Text = alignment.Description;
                        AlignEffectsLabel.Text = "";
                        foreach (var effect in alignment.Effects)
                        {
                            var effectProto = _prototypeManager.Index<BackgroundEffectPrototype>(effect);
                            AlignEffectsLabel.Text += $"\n{effectProto.Description}";
                        }
                    }
                }
            }
            else
            {
                AlignmentButton.SelectId(0);
                AlignTitleLabel.Text = string.Empty;
                AlignDescLabel.Text = string.Empty;
                AlignEffectsLabel.Text = string.Empty;
            }
            CheckReady();
            RefreshBackgroundTraits();
        }

        /// <summary>
        /// Sets the editor to the specified profile with the specified slot.
        /// </summary>
        public void SetProfile(HumanoidCharacterProfile? profile, int? slot)
        {
            Profile = profile?.Clone();
            CharacterSlot = slot;
            SetDirty();
            JobOverride = null;

            UpdateNameEdit();
            UpdateFlavorTextEdit();
            UpdateSexControls();
            UpdateVoiceControls();
            UpdateGenderControls();
            UpdateSkinColor();
            UpdateSpawnPriorityControls();
            UpdateAgeEdit();
            UpdateEyePickers();
            UpdateSaveButton();
            UpdateMarkings();
            UpdateBackgrounds();

            RefreshAntags();
            RefreshJobs();
            RefreshLoadouts();
            RefreshSpecies();
            RefreshTraits();
            RefreshFlavorText();
            ReloadPreview();


            //if (Profile != null)
            //{
            //    PreferenceUnavailableButton.SelectId((int)Profile.PreferenceUnavailable);
            //}
        }

        /// <summary>
        /// A slim reload that only updates the entity itself and not any of the job entities, etc.
        /// </summary>
        private void ReloadProfilePreview()
        {
            if (Profile == null)
                return;

            SpriteView.ReloadProfilePreview(Profile);

            // Check and set the dirty flag to enable the save/reset buttons as appropriate.
            SetDirty();
        }


        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            if (!disposing)
                return;

            _loadoutWindow?.Dispose();
            _loadoutWindow = null;
        }

        protected override void EnteredTree()
        {
            base.EnteredTree();
            ReloadPreview();
        }

        private void UpdateSaveButton()
        {
    //        SaveButton.Disabled = Profile is null || !IsDirty;
            ResetButton.Disabled = Profile is null || !IsDirty;
        }

        private void SetPreviewRotation(Direction direction)
        {
            SpriteView.OverrideDirection = (Direction)((int)direction % 4 * 2);
        }

    }
}
