using Content.Client.Message;
using Content.Shared.Cargo;
using Content.Shared.Cargo.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using System.Linq;

namespace Content.Client.Cargo.UI;

[GenerateTypedNameReferences]
public sealed partial class BountyEntry : BoxContainer
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    public Action? OnLabelButtonPressed;
    public Action? OnSkipButtonPressed;

    public TimeSpan EndTime;
    public TimeSpan UntilNextSkip;

    public BountyEntry(CargoBountyData bounty, TimeSpan untilNextSkip)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        UntilNextSkip = untilNextSkip;

        if (!_prototype.Resolve<CargoBountyPrototype>(bounty.Bounty, out var bountyPrototype))
            return;
        IdLabel.SetMarkup(Loc.GetString("bounty-console-id-label", ("id", bounty.Id)));
        var items = new List<string>();
        foreach (var entry in bountyPrototype.Entries)
        {
            items.Add(Loc.GetString("bounty-console-manifest-entry",
                ("amount", entry.Amount),
                ("item", Loc.GetString(entry.Name))));
        }
        ManifestLabel.SetMarkup(Loc.GetString("bounty-console-manifest-label", ("item", string.Join(", ", items))));
        if (bountyPrototype.BountyType == BountyType.PayOnComplete)
        {
            RewardLabel.SetMarkup(Loc.GetString("bounty-console-reward-label", ("reward", bountyPrototype.Reward)));
            DescriptionLabel.SetMarkup(Loc.GetString("bounty-console-description-label", ("description", Loc.GetString(bountyPrototype.Description))));
            LevelBar.Visible = false;

        }
        if (bountyPrototype.BountyType == BountyType.PayPer || bountyPrototype.BountyType == BountyType.PayPerReagent || bountyPrototype.BountyType == BountyType.PayPerGas)
        {
            LevelBar.Visible = true;
            RewardLabel.SetMarkup($"Price Per Unit: [color=limegreen]${bountyPrototype.Reward}[/color]");
            var entry = bountyPrototype.Entries.FirstOrDefault();
            LevelBar.MaxValue = entry.Amount;
            LevelBar.Value = bounty.AmountCompleted;
            LevelBarText.Text = $"{bounty.AmountCompleted} / {entry.Amount}";
        }
        PrintButton.OnPressed += _ => OnLabelButtonPressed?.Invoke();
    }
}
