using Content.Client.Chemistry.EntitySystems;
using Content.Client.Guidebook.Richtext;
using Content.Client.Message;
using Content.Client.UserInterface.ControlExtensions;
using Content.Shared.CCVar;
using Content.Shared.Botany;
using Content.Shared.Localizations;
using Content.Shared.Metabolism;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using System.Diagnostics.CodeAnalysis;
using System.Linq;

namespace Content.Client.Guidebook.Controls;

/// <summary>
///     Control for embedding a reagent into a guidebook.
/// </summary>
[UsedImplicitly, GenerateTypedNameReferences]
public sealed partial class GuidePlantNutrientEmbed : BoxContainer, IDocumentTag, ISearchableControl, IPrototypeRepresentationControl
{
    [Dependency] private readonly IEntitySystemManager _systemManager = default!;
    [Dependency] private readonly ILogManager _logManager = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly IConfigurationManager _config = default!;

    //private readonly ChemistryGuideDataSystem _chemistryGuideData;
    private readonly ISawmill _sawmill;

    public IPrototype? RepresentedPrototype { get; private set; }

    public GuidePlantNutrientEmbed()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _sawmill = _logManager.GetSawmill("guidebook.reagent");
        //_chemistryGuideData = _systemManager.GetEntitySystem<ChemistryGuideDataSystem>();
        MouseFilter = MouseFilterMode.Stop;
    }

    public GuidePlantNutrientEmbed(string nutrient) : this()
    {
        GenerateControl(_prototype.Index<PlantNutrientPrototype>(nutrient));
    }

    public GuidePlantNutrientEmbed(PlantNutrientPrototype nutrient) : this()
    {
        GenerateControl(nutrient);
    }

    public bool CheckMatchesSearch(string query)
    {
        return this.ChildrenContainText(query);
    }

    public void SetHiddenState(bool state, string query)
    {
        Visible = CheckMatchesSearch(query) ? state : !state;
    }

    public bool TryParseTag(Dictionary<string, string> args, [NotNullWhen(true)] out Control? control)
    {
        control = null;
        if (!args.TryGetValue("Reagent", out var id))
        {
            _sawmill.Error("Reagent embed tag is missing reagent prototype argument");
            return false;
        }

        if (!_prototype.TryIndex<PlantNutrientPrototype>(id, out var nutrient))
        {
            _sawmill.Error($"Specified reagent prototype \"{id}\" is not a valid reagent prototype");
            return false;
        }

        GenerateControl(nutrient);

        control = this;
        return true;
    }

    private void GenerateControl(PlantNutrientPrototype nutrient)
    {
        RepresentedPrototype = nutrient;

        NameBackground.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = nutrient.SubstanceColor
        };

        var r = nutrient.SubstanceColor.R;
        var g = nutrient.SubstanceColor.G;
        var b = nutrient.SubstanceColor.B;

        var textColor = 0.2126f * r + 0.7152f * g + 0.0722f * b > 0.5
            ? Color.Black
            : Color.White;

        ReagentName.SetMarkup(Loc.GetString("guidebook-reagent-name",
            ("color", textColor), ("name", nutrient.LocalizedName)));

        #region Effects
        /*if (_chemistryGuideData.ReagentGuideRegistry.TryGetValue(reagent.ID, out var guideEntryRegistry) &&
            guideEntryRegistry.GuideEntries != null &&
            guideEntryRegistry.GuideEntries.Values.Any(pair => pair.EffectDescriptions.Any() || pair.Metabolites?.Any() == true))
        {
            EffectsDescriptionContainer.Children.Clear();
            foreach (var (stage, effect) in guideEntryRegistry.GuideEntries)
            {
                var hasMetabolites = effect.Metabolites?.Any() == true;
                if (!effect.EffectDescriptions.Any() && !hasMetabolites)
                    continue;

                var groupLabel = new RichTextLabel();
                groupLabel.SetMarkup(Loc.GetString("guidebook-reagent-effects-metabolism-stage-rate",
                    ("stage", _prototype.Index<MetabolismStagePrototype>(stage).LocalizedName), ("rate", effect.MetabolismRate)));
                var descriptionLabel = new RichTextLabel
                {
                    Margin = new Thickness(25, 0, 10, 0)
                };

                var descMsg = new FormattedMessage();
                var descriptionsCount = effect.EffectDescriptions.Length;
                var i = 0;
                foreach (var effectString in effect.EffectDescriptions)
                {
                    descMsg.AddMarkupOrThrow(effectString);
                    i++;
                    if (i < descriptionsCount || hasMetabolites)
                        descMsg.PushNewline();
                }
                if (hasMetabolites)
                {
                    var metabolites = new List<string>();
                    foreach (var (metabolite, ratio) in effect.Metabolites!)
                    {
                        metabolites.Add(Loc.GetString("guidebook-reagent-effects-metabolite-item", ("rate", (double)ratio), ("reagent", _prototype.Index(metabolite).LocalizedName)));
                    }
                    metabolites.Sort();

                    descMsg.AddMarkupOrThrow(Loc.GetString("guidebook-reagent-effects-metabolites", ("items", ContentLocalizationManager.FormatList(metabolites))));
                }
                descriptionLabel.SetMessage(descMsg);

                EffectsDescriptionContainer.AddChild(groupLabel);
                EffectsDescriptionContainer.AddChild(descriptionLabel);
            }
        }
        else
        {
            EffectsContainer.Visible = false;
        }*/
        #endregion

        //GenerateSources(reagent);

        FormattedMessage description = new();
        description.AddText(nutrient.LocalizedDescription);
        description.PushNewline();
        /*description.AddMarkupOrThrow(Loc.GetString("guidebook-reagent-physical-description",
            ("description", nutrient.LocalizedPhysicalDescription)));*/

        ReagentDescription.SetMessage(description);
    }

    /*private void GenerateSources(ReagentPrototype reagent)
    {
        var sources = _chemistryGuideData.GetReagentSources(reagent.ID);
        if (sources.Count == 0)
        {
            SourcesContainer.Visible = false;
            return;
        }
        SourcesContainer.Visible = true;

        var orderedSources = sources
            .OrderBy(o => o.OutputCount)
            .ThenBy(o => o.IdentifierString);
        foreach (var source in orderedSources)
        {
            if (source is ReagentEntitySourceData entitySourceData)
            {
                SourcesDescriptionContainer.AddChild(new GuideReagentReaction(
                    entitySourceData.SourceEntProto,
                    entitySourceData.Solution,
                    entitySourceData.MixingType,
                    _prototype,
                    _systemManager));
            }
            else if (source is ReagentReactionSourceData reactionSourceData)
            {
                SourcesDescriptionContainer.AddChild(new GuideReagentReaction(
                    reactionSourceData.ReactionPrototype,
                    _prototype,
                    _systemManager));
            }
            else if (source is ReagentGasSourceData gasSourceData)
            {
                SourcesDescriptionContainer.AddChild(new GuideReagentReaction(
                    gasSourceData.GasPrototype,
                    gasSourceData.MixingType,
                    _prototype,
                    _systemManager));
            }
        }
    }*/
}
